export const job = {
  id: 30,
  title: "Product Designer Intern",
  description:
    "Magang 4 bulan di tim desain produk marketplace. Kamu akan terlibat dalam proyek nyata mulai dari riset hingga desain fitur yang dipakai jutaan pengguna.",
  requirements:
    "- Mahasiswa aktif atau fresh graduate jurusan Desain, Informatika, atau sejenisnya\n- Portofolio UI/UX (proyek kuliah atau pribadi)\n- Familiar dengan Figma\n- Bersedia magang full-time selama 4 bulan",
  responsibilities:
    "- Membantu membuat wireframe dan prototipe\n- Mengikuti sesi riset dan usability testing\n- Mendokumentasikan komponen design system",
  benefits:
    "- Uang saku bulanan\n- Mentoring dari Senior Product Designer\n- Sertifikat magang\n- Peluang menjadi karyawan tetap",
  company: {
    id: 6,
    name: "PT Toko Kita Commerce",
    slug: "pt-toko-kita-commerce",
    tagline: "Belanja mudah, UMKM bertumbuh",
    description:
      "PT Toko Kita Commerce adalah marketplace yang berfokus memberdayakan UMKM lokal dengan lebih dari 150.000 penjual aktif dan 8 juta pengguna bulanan.",
    logoUrl:
      "https://ui-avatars.com/api/?name=Toko+Kita+Commerce&background=F97316&color=fff&size=256&bold=true",
    coverImageUrl: "https://picsum.photos/seed/toko-kita-commerce/1200/400",
    website: "https://www.tokokitacommerce.com",
    email: "hr@tokokitacommerce.com",
    phone: "0215556677",
    foundedYear: 2015,
    companySize: "LARGE",
    companyType: "PRIVATE",
    industryType: "E_COMMERCE",
    status: "ACTIVE",
    verified: true,
    active: true,
    ownerId: 7,
    socialLinks: [
      {
        platform: "LINKEDIN",
        url: "https://linkedin.com/company/toko-kita-commerce",
      },
      {
        platform: "INSTAGRAM",
        url: "https://instagram.com/tokokitacommerce",
      },
      {
        platform: "WEBSITE",
        url: "https://www.tokokitacommerce.com",
      },
    ],
    createdAt: "2026-09-21T06:10:13.036633Z",
    updatedAt: "2026-09-21T06:12:58.220344Z",
  },
  employerId: 7,
  category: {
    id: 8,
    name: "UI/UX Design",
    slug: "ui-ux-design",
    description:
      "Perancangan pengalaman dan antarmuka pengguna, mulai dari riset, wireframe, prototipe, hingga design system.",
    iconUrl: "https://api.iconify.design/tabler/palette.svg",
    active: true,
    parentId: 11,
    parentName: "Design & Creative",
    subCategories: [],
    createdAt: "2026-09-25T00:23:36.005262Z",
  },
  skills: [
    {
      id: 27,
      name: "Figma",
      slug: "figma",
      category: "TOOL",
      active: true,
    },
    {
      id: 40,
      name: "Teamwork",
      slug: "teamwork",
      category: "SOFT_SKILL",
      active: true,
    },
  ],
  tags: [
    {
      id: 3,
      name: "Fresh Graduate",
      slug: "fresh-graduate",
      active: true,
    },
  ],
  address: "Jl. Letjen S. Parman Kav. 28, APL Tower Lt. 18",
  city: "Jakarta Barat",
  state: "DKI Jakarta",
  country: "Indonesia",
  zipCode: "11470",
  minSalary: 3000000,
  maxSalary: 4000000,
  currency: "IDR",
  salaryNegotiable: true,
  salaryDisclosed: true,
  jobType: "INTERNSHIP",
  workMode: "ONSITE",
  experienceLevel: "ENTRY_LEVEL",
  status: "OPEN",
  openings: 3,
  applicationDeadline: "2026-10-28",
  expiresAt: "2026-11-28",
  active: true,
  viewCount: 350,
  applicationCount: 32,
  createdAt: "2026-09-25T11:55:30.207130Z",
  updatedAt: "2026-09-25T11:57:30.281330Z",
  publishedAt: "2026-09-25T11:57:30.281330Z",
  closedAt: null,
};
