export const categories = [
  {
    id: 1,
    name: "Software Development",
    slug: "software-development",
    description:
      "Pekerjaan di bidang rekayasa perangkat lunak, mulai dari frontend, backend, mobile, hingga infrastruktur dan keamanan aplikasi.",
    iconUrl: "https://api.iconify.design/tabler/terminal-2.svg",
    active: true,
    parentId: null,
    parentName: null,
    subCategories: [
      {
        id: 2,
        name: "Frontend Development",
        slug: "frontend-development",
        description:
          "Kategori yang mencakup pengembangan antarmuka pengguna (UI) menggunakan teknologi web seperti HTML, CSS, JavaScript, dan framework modern seperti React, Vue, dan Angular.",
        iconUrl: "https://api.iconify.design/tabler/code.svg",
        active: true,
        parentId: 1,
        parentName: "Software Development",
        subCategories: [],
        createdAt: "2026-09-25T00:17:36.005262Z",
      },
      {
        id: 3,
        name: "Mobile Development",
        slug: "mobile-development",
        description:
          "Pengembangan aplikasi mobile untuk Android dan iOS, baik native (Kotlin, Swift) maupun cross-platform (Flutter, React Native).",
        iconUrl: "https://api.iconify.design/tabler/device-mobile.svg",
        active: true,
        parentId: 1,
        parentName: "Software Development",
        subCategories: [],
        createdAt: "2026-09-25T00:18:36.005262Z",
      },
      {
        id: 4,
        name: "Backend Development",
        slug: "backend-development",
        description:
          "Pekerjaan yang berfokus pada pengembangan sisi server, logika bisnis, RESTful API, dan manajemen database menggunakan teknologi seperti Java, Node.js, Python, dan Spring Boot.",
        iconUrl: "https://api.iconify.design/tabler/server.svg",
        active: true,
        parentId: 1,
        parentName: "Software Development",
        subCategories: [],
        createdAt: "2026-09-25T00:19:36.005262Z",
      },
      {
        id: 5,
        name: "DevOps & Cloud",
        slug: "devops-cloud",
        description:
          "Pengelolaan infrastruktur, CI/CD, containerization, dan layanan cloud untuk memastikan aplikasi berjalan andal dan scalable.",
        iconUrl: "https://api.iconify.design/tabler/cloud-computing.svg",
        active: true,
        parentId: 1,
        parentName: "Software Development",
        subCategories: [],
        createdAt: "2026-09-25T00:20:36.005262Z",
      },
      {
        id: 6,
        name: "Quality Assurance",
        slug: "quality-assurance",
        description:
          "Pengujian perangkat lunak secara manual maupun otomatis untuk memastikan kualitas dan keandalan produk.",
        iconUrl: "https://api.iconify.design/tabler/bug.svg",
        active: true,
        parentId: 1,
        parentName: "Software Development",
        subCategories: [],
        createdAt: "2026-09-25T00:21:36.005262Z",
      },
      {
        id: 14,
        name: "Cyber Security",
        slug: "cyber-security",
        description:
          "Perlindungan sistem, jaringan, dan data dari ancaman siber melalui pengujian keamanan dan monitoring.",
        iconUrl: "https://api.iconify.design/tabler/shield-lock.svg",
        active: true,
        parentId: 1,
        parentName: "Software Development",
        subCategories: [],
        createdAt: "2026-09-25T00:29:36.005262Z",
      },
      {
        id: 19,
        name: "Fullstack Development",
        slug: "fullstack-development",
        description:
          "Pekerjaan yang mencakup pengembangan frontend dan backend sekaligus, dari antarmuka pengguna hingga API dan database.",
        iconUrl: "https://api.iconify.design/tabler/stack-2.svg",
        active: true,
        parentId: 1,
        parentName: "Software Development",
        subCategories: [],
        createdAt: "2026-08-12T02:39:38.955123Z",
      },
      {
        id: 20,
        name: "Game Development",
        slug: "game-development",
        description:
          "Pekerjaan merancang dan membangun game untuk mobile, PC, maupun konsol menggunakan engine seperti Unity dan Unreal.",
        iconUrl: "https://api.iconify.design/tabler/device-gamepad-2.svg",
        active: true,
        parentId: 1,
        parentName: "Software Development",
        subCategories: [],
        createdAt: "2026-08-12T03:26:52.534123Z",
      },
    ],
    createdAt: "2026-08-12T01:52:25.376123Z",
  },
  {
    id: 2,
    name: "Frontend Development",
    slug: "frontend-development",
    description:
      "Kategori yang mencakup pengembangan antarmuka pengguna (UI) menggunakan teknologi web seperti HTML, CSS, JavaScript, dan framework modern seperti React, Vue, dan Angular.",
    iconUrl: "https://api.iconify.design/tabler/code.svg",
    active: true,
    parentId: 1,
    parentName: "Software Development",
    subCategories: [],
    createdAt: "2026-09-25T00:17:36.005262Z",
  },
  {
    id: 3,
    name: "Mobile Development",
    slug: "mobile-development",
    description:
      "Pengembangan aplikasi mobile untuk Android dan iOS, baik native (Kotlin, Swift) maupun cross-platform (Flutter, React Native).",
    iconUrl: "https://api.iconify.design/tabler/device-mobile.svg",
    active: true,
    parentId: 1,
    parentName: "Software Development",
    subCategories: [],
    createdAt: "2026-09-25T00:18:36.005262Z",
  },
  {
    id: 4,
    name: "Backend Development",
    slug: "backend-development",
    description:
      "Pekerjaan yang berfokus pada pengembangan sisi server, logika bisnis, RESTful API, dan manajemen database menggunakan teknologi seperti Java, Node.js, Python, dan Spring Boot.",
    iconUrl: "https://api.iconify.design/tabler/server.svg",
    active: true,
    parentId: 1,
    parentName: "Software Development",
    subCategories: [],
    createdAt: "2026-09-25T00:19:36.005262Z",
  },
  {
    id: 5,
    name: "DevOps & Cloud",
    slug: "devops-cloud",
    description:
      "Pengelolaan infrastruktur, CI/CD, containerization, dan layanan cloud untuk memastikan aplikasi berjalan andal dan scalable.",
    iconUrl: "https://api.iconify.design/tabler/cloud-computing.svg",
    active: true,
    parentId: 1,
    parentName: "Software Development",
    subCategories: [],
    createdAt: "2026-09-25T00:20:36.005262Z",
  },
  {
    id: 6,
    name: "Quality Assurance",
    slug: "quality-assurance",
    description:
      "Pengujian perangkat lunak secara manual maupun otomatis untuk memastikan kualitas dan keandalan produk.",
    iconUrl: "https://api.iconify.design/tabler/bug.svg",
    active: true,
    parentId: 1,
    parentName: "Software Development",
    subCategories: [],
    createdAt: "2026-09-25T00:21:36.005262Z",
  },
  {
    id: 14,
    name: "Cyber Security",
    slug: "cyber-security",
    description:
      "Perlindungan sistem, jaringan, dan data dari ancaman siber melalui pengujian keamanan dan monitoring.",
    iconUrl: "https://api.iconify.design/tabler/shield-lock.svg",
    active: true,
    parentId: 1,
    parentName: "Software Development",
    subCategories: [],
    createdAt: "2026-09-25T00:29:36.005262Z",
  },
  {
    id: 19,
    name: "Fullstack Development",
    slug: "fullstack-development",
    description:
      "Pekerjaan yang mencakup pengembangan frontend dan backend sekaligus, dari antarmuka pengguna hingga API dan database.",
    iconUrl: "https://api.iconify.design/tabler/stack-2.svg",
    active: true,
    parentId: 1,
    parentName: "Software Development",
    subCategories: [],
    createdAt: "2026-08-12T02:39:38.955123Z",
  },
  {
    id: 20,
    name: "Game Development",
    slug: "game-development",
    description:
      "Pekerjaan merancang dan membangun game untuk mobile, PC, maupun konsol menggunakan engine seperti Unity dan Unreal.",
    iconUrl: "https://api.iconify.design/tabler/device-gamepad-2.svg",
    active: true,
    parentId: 1,
    parentName: "Software Development",
    subCategories: [],
    createdAt: "2026-08-12T03:26:52.534123Z",
  },
  {
    id: 10,
    name: "Data & Analytics",
    slug: "data-analytics",
    description:
      "Pekerjaan yang berfokus pada pengolahan, analisis, dan pemanfaatan data untuk mendukung pengambilan keputusan bisnis.",
    iconUrl: "https://api.iconify.design/tabler/chart-dots.svg",
    active: true,
    parentId: null,
    parentName: null,
    subCategories: [
      {
        id: 7,
        name: "Data & AI",
        slug: "data-ai",
        description:
          "Pekerjaan di bidang data engineering, data analysis, data science, dan machine learning.",
        iconUrl: "https://api.iconify.design/tabler/brain.svg",
        active: true,
        parentId: 10,
        parentName: "Data & Analytics",
        subCategories: [],
        createdAt: "2026-09-25T00:22:36.005262Z",
      },
      {
        id: 21,
        name: "Data Engineering",
        slug: "data-engineering",
        description:
          "Pekerjaan membangun dan memelihara pipeline data, data warehouse, dan infrastruktur pemrosesan data berskala besar.",
        iconUrl: "https://api.iconify.design/tabler/database.svg",
        active: true,
        parentId: 10,
        parentName: "Data & Analytics",
        subCategories: [],
        createdAt: "2026-08-12T05:01:19.692123Z",
      },
      {
        id: 22,
        name: "Business Intelligence",
        slug: "business-intelligence",
        description:
          "Pekerjaan menyusun dashboard, laporan, dan analisis bisnis menggunakan tools seperti Power BI, Tableau, dan Looker.",
        iconUrl: "https://api.iconify.design/tabler/chart-bar.svg",
        active: true,
        parentId: 10,
        parentName: "Data & Analytics",
        subCategories: [],
        createdAt: "2026-08-12T05:48:33.271123Z",
      },
    ],
    createdAt: "2026-08-12T04:14:06.113123Z",
  },
  {
    id: 7,
    name: "Data & AI",
    slug: "data-ai",
    description:
      "Pekerjaan di bidang data engineering, data analysis, data science, dan machine learning.",
    iconUrl: "https://api.iconify.design/tabler/brain.svg",
    active: true,
    parentId: 10,
    parentName: "Data & Analytics",
    subCategories: [],
    createdAt: "2026-09-25T00:22:36.005262Z",
  },
  {
    id: 21,
    name: "Data Engineering",
    slug: "data-engineering",
    description:
      "Pekerjaan membangun dan memelihara pipeline data, data warehouse, dan infrastruktur pemrosesan data berskala besar.",
    iconUrl: "https://api.iconify.design/tabler/database.svg",
    active: true,
    parentId: 10,
    parentName: "Data & Analytics",
    subCategories: [],
    createdAt: "2026-08-12T05:01:19.692123Z",
  },
  {
    id: 22,
    name: "Business Intelligence",
    slug: "business-intelligence",
    description:
      "Pekerjaan menyusun dashboard, laporan, dan analisis bisnis menggunakan tools seperti Power BI, Tableau, dan Looker.",
    iconUrl: "https://api.iconify.design/tabler/chart-bar.svg",
    active: true,
    parentId: 10,
    parentName: "Data & Analytics",
    subCategories: [],
    createdAt: "2026-08-12T05:48:33.271123Z",
  },
  {
    id: 11,
    name: "Design & Creative",
    slug: "design-creative",
    description:
      "Pekerjaan di bidang desain visual, pengalaman pengguna, dan produksi konten kreatif.",
    iconUrl: "https://api.iconify.design/tabler/color-swatch.svg",
    active: true,
    parentId: null,
    parentName: null,
    subCategories: [
      {
        id: 8,
        name: "UI/UX Design",
        slug: "ui-ux-design",
        description:
          "Perancangan pengalaman dan antarmuka pengguna, mulai dari riset, wireframe, prototipe, hingga design system.",
        iconUrl: "https://api.iconify.design/tabler/palette.svg",
        active: true,
        parentId: 11,
        parentName: "Design & Creative",
        subCategories: [],
        createdAt: "2026-09-25T00:23:36.005262Z",
      },
      {
        id: 23,
        name: "Graphic Design",
        slug: "graphic-design",
        description:
          "Pekerjaan membuat materi visual seperti logo, materi promosi, dan aset brand untuk kebutuhan digital maupun cetak.",
        iconUrl: "https://api.iconify.design/tabler/brush.svg",
        active: true,
        parentId: 11,
        parentName: "Design & Creative",
        subCategories: [],
        createdAt: "2026-08-12T07:23:00.429123Z",
      },
      {
        id: 24,
        name: "Video & Motion Graphics",
        slug: "video-motion-graphics",
        description:
          "Pekerjaan memproduksi, mengedit video, dan membuat animasi motion graphics untuk konten pemasaran dan produk.",
        iconUrl: "https://api.iconify.design/tabler/movie.svg",
        active: true,
        parentId: 11,
        parentName: "Design & Creative",
        subCategories: [],
        createdAt: "2026-08-12T08:10:14.008123Z",
      },
    ],
    createdAt: "2026-08-12T06:35:46.850123Z",
  },
  {
    id: 8,
    name: "UI/UX Design",
    slug: "ui-ux-design",
    description:
      "Perancangan pengalaman dan antarmuka pengguna, mulai dari riset, wireframe, prototipe, hingga design system.",
    iconUrl: "https://api.iconify.design/tabler/palette.svg",
    active: true,
    parentId: 11,
    parentName: "Design & Creative",
    subCategories: [],
    createdAt: "2026-09-25T00:23:36.005262Z",
  },
  {
    id: 23,
    name: "Graphic Design",
    slug: "graphic-design",
    description:
      "Pekerjaan membuat materi visual seperti logo, materi promosi, dan aset brand untuk kebutuhan digital maupun cetak.",
    iconUrl: "https://api.iconify.design/tabler/brush.svg",
    active: true,
    parentId: 11,
    parentName: "Design & Creative",
    subCategories: [],
    createdAt: "2026-08-12T07:23:00.429123Z",
  },
  {
    id: 24,
    name: "Video & Motion Graphics",
    slug: "video-motion-graphics",
    description:
      "Pekerjaan memproduksi, mengedit video, dan membuat animasi motion graphics untuk konten pemasaran dan produk.",
    iconUrl: "https://api.iconify.design/tabler/movie.svg",
    active: true,
    parentId: 11,
    parentName: "Design & Creative",
    subCategories: [],
    createdAt: "2026-08-12T08:10:14.008123Z",
  },
  {
    id: 12,
    name: "Product & Business",
    slug: "product-business",
    description:
      "Pekerjaan yang berkaitan dengan pengelolaan produk, strategi bisnis, pemasaran, dan pengembangan kemitraan.",
    iconUrl: "https://api.iconify.design/tabler/briefcase-2.svg",
    active: true,
    parentId: null,
    parentName: null,
    subCategories: [
      {
        id: 9,
        name: "Product Management",
        slug: "product-management",
        description:
          "Pengelolaan siklus hidup produk digital, mulai dari discovery, roadmap, hingga peluncuran fitur.",
        iconUrl: "https://api.iconify.design/tabler/layout-kanban.svg",
        active: true,
        parentId: 12,
        parentName: "Product & Business",
        subCategories: [],
        createdAt: "2026-09-25T00:24:36.005262Z",
      },
      {
        id: 13,
        name: "Digital Marketing",
        slug: "digital-marketing",
        description:
          "Pemasaran digital meliputi SEO, SEM, social media, content marketing, dan performance marketing.",
        iconUrl: "https://api.iconify.design/tabler/speakerphone.svg",
        active: true,
        parentId: 12,
        parentName: "Product & Business",
        subCategories: [],
        createdAt: "2026-09-25T00:28:36.005262Z",
      },
      {
        id: 25,
        name: "Project Management",
        slug: "project-management",
        description:
          "Pekerjaan merencanakan, mengoordinasikan, dan memantau jalannya proyek agar selesai tepat waktu dan sesuai anggaran.",
        iconUrl: "https://api.iconify.design/tabler/clipboard-list.svg",
        active: true,
        parentId: 12,
        parentName: "Product & Business",
        subCategories: [],
        createdAt: "2026-08-12T09:44:41.166123Z",
      },
      {
        id: 26,
        name: "Business Development",
        slug: "business-development",
        description:
          "Pekerjaan mencari peluang bisnis baru, membangun kemitraan strategis, dan memperluas pasar perusahaan.",
        iconUrl: "https://api.iconify.design/tabler/briefcase.svg",
        active: true,
        parentId: 12,
        parentName: "Product & Business",
        subCategories: [],
        createdAt: "2026-08-12T10:31:54.745123Z",
      },
    ],
    createdAt: "2026-08-12T08:57:27.587123Z",
  },
  {
    id: 9,
    name: "Product Management",
    slug: "product-management",
    description:
      "Pengelolaan siklus hidup produk digital, mulai dari discovery, roadmap, hingga peluncuran fitur.",
    iconUrl: "https://api.iconify.design/tabler/layout-kanban.svg",
    active: true,
    parentId: 12,
    parentName: "Product & Business",
    subCategories: [],
    createdAt: "2026-09-25T00:24:36.005262Z",
  },
  {
    id: 13,
    name: "Digital Marketing",
    slug: "digital-marketing",
    description:
      "Pemasaran digital meliputi SEO, SEM, social media, content marketing, dan performance marketing.",
    iconUrl: "https://api.iconify.design/tabler/speakerphone.svg",
    active: true,
    parentId: 12,
    parentName: "Product & Business",
    subCategories: [],
    createdAt: "2026-09-25T00:28:36.005262Z",
  },
  {
    id: 25,
    name: "Project Management",
    slug: "project-management",
    description:
      "Pekerjaan merencanakan, mengoordinasikan, dan memantau jalannya proyek agar selesai tepat waktu dan sesuai anggaran.",
    iconUrl: "https://api.iconify.design/tabler/clipboard-list.svg",
    active: true,
    parentId: 12,
    parentName: "Product & Business",
    subCategories: [],
    createdAt: "2026-08-12T09:44:41.166123Z",
  },
  {
    id: 26,
    name: "Business Development",
    slug: "business-development",
    description:
      "Pekerjaan mencari peluang bisnis baru, membangun kemitraan strategis, dan memperluas pasar perusahaan.",
    iconUrl: "https://api.iconify.design/tabler/briefcase.svg",
    active: true,
    parentId: 12,
    parentName: "Product & Business",
    subCategories: [],
    createdAt: "2026-08-12T10:31:54.745123Z",
  },
  {
    id: 15,
    name: "Finance & Accounting",
    slug: "finance-accounting",
    description:
      "Pekerjaan di bidang keuangan, akuntansi, perpajakan, dan analisis finansial perusahaan.",
    iconUrl: "https://api.iconify.design/tabler/coin.svg",
    active: true,
    parentId: null,
    parentName: null,
    subCategories: [
      {
        id: 27,
        name: "Accounting",
        slug: "accounting",
        description:
          "Pekerjaan mencatat transaksi, menyusun laporan keuangan, dan memastikan pembukuan sesuai standar akuntansi.",
        iconUrl: "https://api.iconify.design/tabler/calculator.svg",
        active: true,
        parentId: 15,
        parentName: "Finance & Accounting",
        subCategories: [],
        createdAt: "2026-08-12T12:06:21.903123Z",
      },
      {
        id: 28,
        name: "Financial Analysis",
        slug: "financial-analysis",
        description:
          "Pekerjaan menganalisis kinerja keuangan, menyusun proyeksi, dan memberi rekomendasi investasi maupun anggaran.",
        iconUrl: "https://api.iconify.design/tabler/chart-line.svg",
        active: true,
        parentId: 15,
        parentName: "Finance & Accounting",
        subCategories: [],
        createdAt: "2026-08-12T12:53:35.482123Z",
      },
      {
        id: 29,
        name: "Tax",
        slug: "tax",
        description:
          "Pekerjaan mengelola kewajiban perpajakan perusahaan, termasuk perhitungan, pelaporan, dan perencanaan pajak.",
        iconUrl: "https://api.iconify.design/tabler/receipt-tax.svg",
        active: true,
        parentId: 15,
        parentName: "Finance & Accounting",
        subCategories: [],
        createdAt: "2026-08-12T13:40:49.061123Z",
      },
    ],
    createdAt: "2026-08-12T11:19:08.324123Z",
  },
  {
    id: 27,
    name: "Accounting",
    slug: "accounting",
    description:
      "Pekerjaan mencatat transaksi, menyusun laporan keuangan, dan memastikan pembukuan sesuai standar akuntansi.",
    iconUrl: "https://api.iconify.design/tabler/calculator.svg",
    active: true,
    parentId: 15,
    parentName: "Finance & Accounting",
    subCategories: [],
    createdAt: "2026-08-12T12:06:21.903123Z",
  },
  {
    id: 28,
    name: "Financial Analysis",
    slug: "financial-analysis",
    description:
      "Pekerjaan menganalisis kinerja keuangan, menyusun proyeksi, dan memberi rekomendasi investasi maupun anggaran.",
    iconUrl: "https://api.iconify.design/tabler/chart-line.svg",
    active: true,
    parentId: 15,
    parentName: "Finance & Accounting",
    subCategories: [],
    createdAt: "2026-08-12T12:53:35.482123Z",
  },
  {
    id: 29,
    name: "Tax",
    slug: "tax",
    description:
      "Pekerjaan mengelola kewajiban perpajakan perusahaan, termasuk perhitungan, pelaporan, dan perencanaan pajak.",
    iconUrl: "https://api.iconify.design/tabler/receipt-tax.svg",
    active: true,
    parentId: 15,
    parentName: "Finance & Accounting",
    subCategories: [],
    createdAt: "2026-08-12T13:40:49.061123Z",
  },
  {
    id: 16,
    name: "Human Resources",
    slug: "human-resources",
    description:
      "Pekerjaan yang berkaitan dengan pengelolaan sumber daya manusia, rekrutmen, dan budaya perusahaan.",
    iconUrl: "https://api.iconify.design/tabler/users-group.svg",
    active: true,
    parentId: null,
    parentName: null,
    subCategories: [
      {
        id: 30,
        name: "Recruitment & Talent Acquisition",
        slug: "recruitment-talent-acquisition",
        description:
          "Pekerjaan mencari, menyaring, dan merekrut kandidat terbaik sesuai kebutuhan perusahaan.",
        iconUrl: "https://api.iconify.design/tabler/user-search.svg",
        active: true,
        parentId: 16,
        parentName: "Human Resources",
        subCategories: [],
        createdAt: "2026-08-12T15:15:16.219123Z",
      },
      {
        id: 31,
        name: "People Operations",
        slug: "people-operations",
        description:
          "Pekerjaan mengelola administrasi karyawan, payroll, benefit, serta program pengembangan dan engagement karyawan.",
        iconUrl: "https://api.iconify.design/tabler/users.svg",
        active: true,
        parentId: 16,
        parentName: "Human Resources",
        subCategories: [],
        createdAt: "2026-08-12T16:02:29.798123Z",
      },
    ],
    createdAt: "2026-08-12T14:28:02.640123Z",
  },
  {
    id: 30,
    name: "Recruitment & Talent Acquisition",
    slug: "recruitment-talent-acquisition",
    description:
      "Pekerjaan mencari, menyaring, dan merekrut kandidat terbaik sesuai kebutuhan perusahaan.",
    iconUrl: "https://api.iconify.design/tabler/user-search.svg",
    active: true,
    parentId: 16,
    parentName: "Human Resources",
    subCategories: [],
    createdAt: "2026-08-12T15:15:16.219123Z",
  },
  {
    id: 31,
    name: "People Operations",
    slug: "people-operations",
    description:
      "Pekerjaan mengelola administrasi karyawan, payroll, benefit, serta program pengembangan dan engagement karyawan.",
    iconUrl: "https://api.iconify.design/tabler/users.svg",
    active: true,
    parentId: 16,
    parentName: "Human Resources",
    subCategories: [],
    createdAt: "2026-08-12T16:02:29.798123Z",
  },
  {
    id: 17,
    name: "Customer Service",
    slug: "customer-service",
    description:
      "Pekerjaan melayani dan membantu pelanggan agar mendapatkan pengalaman terbaik dengan produk atau layanan.",
    iconUrl: "https://api.iconify.design/tabler/message-circle.svg",
    active: true,
    parentId: null,
    parentName: null,
    subCategories: [
      {
        id: 32,
        name: "Customer Support",
        slug: "customer-support",
        description:
          "Pekerjaan menjawab pertanyaan dan menyelesaikan kendala pelanggan melalui chat, email, maupun telepon.",
        iconUrl: "https://api.iconify.design/tabler/headset.svg",
        active: true,
        parentId: 17,
        parentName: "Customer Service",
        subCategories: [],
        createdAt: "2026-08-12T17:36:56.956123Z",
      },
      {
        id: 33,
        name: "Customer Success",
        slug: "customer-success",
        description:
          "Pekerjaan mendampingi pelanggan agar berhasil menggunakan produk, menjaga retensi, dan meningkatkan kepuasan pelanggan.",
        iconUrl: "https://api.iconify.design/tabler/heart-handshake.svg",
        active: true,
        parentId: 17,
        parentName: "Customer Service",
        subCategories: [],
        createdAt: "2026-08-12T18:24:10.535123Z",
      },
    ],
    createdAt: "2026-08-12T16:49:43.377123Z",
  },
  {
    id: 32,
    name: "Customer Support",
    slug: "customer-support",
    description:
      "Pekerjaan menjawab pertanyaan dan menyelesaikan kendala pelanggan melalui chat, email, maupun telepon.",
    iconUrl: "https://api.iconify.design/tabler/headset.svg",
    active: true,
    parentId: 17,
    parentName: "Customer Service",
    subCategories: [],
    createdAt: "2026-08-12T17:36:56.956123Z",
  },
  {
    id: 33,
    name: "Customer Success",
    slug: "customer-success",
    description:
      "Pekerjaan mendampingi pelanggan agar berhasil menggunakan produk, menjaga retensi, dan meningkatkan kepuasan pelanggan.",
    iconUrl: "https://api.iconify.design/tabler/heart-handshake.svg",
    active: true,
    parentId: 17,
    parentName: "Customer Service",
    subCategories: [],
    createdAt: "2026-08-12T18:24:10.535123Z",
  },
  {
    id: 18,
    name: "Sales",
    slug: "sales",
    description:
      "Pekerjaan menjual produk atau layanan, mencapai target penjualan, dan menjaga hubungan dengan klien.",
    iconUrl: "https://api.iconify.design/tabler/presentation-analytics.svg",
    active: true,
    parentId: null,
    parentName: null,
    subCategories: [
      {
        id: 34,
        name: "Sales Executive",
        slug: "sales-executive",
        description:
          "Pekerjaan mencari prospek, melakukan presentasi produk, dan menutup penjualan untuk mencapai target.",
        iconUrl: "https://api.iconify.design/tabler/trending-up.svg",
        active: true,
        parentId: 18,
        parentName: "Sales",
        subCategories: [],
        createdAt: "2026-08-12T19:58:37.693123Z",
      },
      {
        id: 35,
        name: "Account Management",
        slug: "account-management",
        description:
          "Pekerjaan mengelola hubungan jangka panjang dengan klien yang sudah ada dan mengembangkan nilai kerja sama.",
        iconUrl: "https://api.iconify.design/tabler/user-check.svg",
        active: true,
        parentId: 18,
        parentName: "Sales",
        subCategories: [],
        createdAt: "2026-08-12T20:45:51.272123Z",
      },
    ],
    createdAt: "2026-08-12T19:11:24.114123Z",
  },
  {
    id: 34,
    name: "Sales Executive",
    slug: "sales-executive",
    description:
      "Pekerjaan mencari prospek, melakukan presentasi produk, dan menutup penjualan untuk mencapai target.",
    iconUrl: "https://api.iconify.design/tabler/trending-up.svg",
    active: true,
    parentId: 18,
    parentName: "Sales",
    subCategories: [],
    createdAt: "2026-08-12T19:58:37.693123Z",
  },
  {
    id: 35,
    name: "Account Management",
    slug: "account-management",
    description:
      "Pekerjaan mengelola hubungan jangka panjang dengan klien yang sudah ada dan mengembangkan nilai kerja sama.",
    iconUrl: "https://api.iconify.design/tabler/user-check.svg",
    active: true,
    parentId: 18,
    parentName: "Sales",
    subCategories: [],
    createdAt: "2026-08-12T20:45:51.272123Z",
  },
];
