export const savedJobs = [
  {
    id: 2,
    candidate: {
      id: 1,
      fullName: "jokowi",
      email: "jokowi@gmail.com",
      phone: "021222333124",
      profileImage: null,
      role: "ROLE_EMPLOYER",
      status: "ACTIVE",
      lastLogin: "2026-07-29T23:49:36.189082Z",
      createdAt: "2026-07-29T23:49:36.268324Z",
    },
    job: {
      id: 2,
      title: "Senior Java backend Developer",
      description:
        "We are looking for a skilled backend developer to build scalable microservices using SpringBoot and Kafka.",
      requirements:
        "5+ years experience in Java, Spring Boot, Microservices, Docker, Kubernetes, Kafka",
      responsibilities:
        "Design APIs, build microservices, optimuze performance, collaborate with frontend team",
      benefits: "Health insurance, flexible working hours, remote work options",
      company: {
        id: 2,
        name: "JoahanWork Technology",
        slug: "joahanwork-technology",
        tagline: "Building scalable microservices & modern web app",
        description: "JoahanWork is a software house company",
        logoUrl:
          "https://ui-avatars.com/api/?name=Joahanwork+Technology&background=0F766E&color=fff&size=256&bold=true",
        coverImageUrl: "https://picsum.photos/seed/joahanwork-technology/1200/400",
        website: "https://www.joahanwork.com",
        email: "contact@joahanwork.com",
        phone: "+62-81222333444",
        foundedYear: 2026,
        companySize: "SMALL",
        companyType: "PRIVATE",
        industryType: "TECHNOLOGY",
        status: "ACTIVE",
        verified: true,
        active: null,
        ownerId: 1,
        socialLinks: [
          {
            platform: "LINKEDIN",
            url: "https://www.joahanwork.com",
          },
          {
            platform: "TWITTER",
            url: "https://www.joahanwork.com",
          },
          {
            platform: "INSTAGRAM",
            url: "https://www.joahanwork.com",
          },
          {
            platform: "FACEBOOK",
            url: "https://www.joahanwork.com",
          },
        ],
        createdAt: "2026-08-08T01:19:20.366366Z",
        updatedAt: "2026-08-08T01:35:14.950046Z",
      },
      employerId: 1,
      category: {
        id: 3,
        name: "Software Development",
        slug: "software-development",
        description:
          "Job related to software engineering, backend, frontend and full-stack development",
        iconUrl: "Icon Job Categories",
        active: true,
        parentId: null,
        parentName: null,
        subCategories: [
          {
            id: 4,
            name: "Backend Developments",
            slug: "backend-development",
            description:
              "Pekerjaan yang berfokus pada pengembangan sisi server, API, dan database.",
            iconUrl: "https://cdn.johanwork.com/icons/backend-development.svg",
            active: true,
            parentId: 3,
            parentName: "Software Development",
            subCategories: [],
            createdAt: "2026-09-22T10:06:59.369165Z",
          },
        ],
        createdAt: "2026-08-12T01:05:11.797565Z",
      },
      skills: [
        {
          id: 2,
          name: "Fast API",
          slug: "fast-api-1",
          category: "FRAMEWORK",
          active: true,
        },
      ],
      tags: [
        {
          id: 2,
          name: "AI/ML",
          slug: "aiml-1",
          active: false,
        },
      ],
      address: "Jakarta IT Park",
      city: "Jakarta",
      state: "DKI Jakarta",
      country: "Indonesia",
      zipCode: "112233",
      minSalary: 8000000.0,
      maxSalary: 15000000.0,
      currency: null,
      salaryNegotiable: null,
      salaryDisclosed: null,
      jobType: "FULL_TIME",
      workMode: "HYBRID",
      experienceLevel: "SENIOR_LEVEL",
      status: "OPEN",
      openings: 3,
      applicationDeadline: "2026-08-12",
      expiresAt: "2026-09-12",
      active: true,
      viewCount: null,
      applicationCount: null,
      createdAt: "2026-08-19T13:06:18.961647Z",
      updatedAt: "2026-08-19T13:06:29.696148Z",
      publishedAt: "2026-08-19T13:06:29.686791Z",
      closedAt: null,
    },
    savedAt: "2026-09-30T13:38:23.965342Z",
  },
  {
    id: 3,
    candidate: {
      id: 1,
      fullName: "jokowi",
      email: "jokowi@gmail.com",
      phone: "021222333124",
      profileImage: null,
      role: "ROLE_EMPLOYER",
      status: "ACTIVE",
      lastLogin: "2026-07-29T23:49:36.189082Z",
      createdAt: "2026-07-29T23:49:36.268324Z",
    },
    job: {
      id: 15,
      title: "Frontend Engineer (Next.js)",
      description: "Bangun halaman produk dan checkout marketplace yang diakses jutaan pengguna setiap bulan. Fokus utama posisi ini adalah performa, SEO, dan konversi.",
      requirements: "- Minimal 3 tahun pengalaman frontend development\n- Menguasai React, Next.js, dan TypeScript\n- Memahami SSR, SSG, dan strategi caching\n- Pengalaman melakukan A/B testing\n- Paham Core Web Vitals dan optimasi performa",
      responsibilities: "- Mengembangkan halaman produk, keranjang, dan checkout\n- Meningkatkan skor Core Web Vitals\n- Menjalankan eksperimen A/B bersama tim Product\n- Melakukan code review",
      benefits: "- Gaji kompetitif dan bonus tahunan\n- Voucher belanja bulanan\n- Asuransi kesehatan untuk karyawan dan keluarga\n- Hybrid 2 hari WFO",
      company: {
        id: 6,
        name: "PT Toko Kita Commerce",
        slug: "pt-toko-kita-commerce",
        tagline: "Belanja mudah, UMKM bertumbuh",
        description: "PT Toko Kita Commerce adalah marketplace yang berfokus memberdayakan UMKM lokal dengan lebih dari 150.000 penjual aktif dan 8 juta pengguna bulanan.",
        logoUrl: "https://ui-avatars.com/api/?name=Toko+Kita+Commerce&background=F97316&color=fff&size=256&bold=true",
        coverImageUrl: "https://picsum.photos/seed/toko-kita-commerce/1200/400",
        website: "https://www.tokokitacommerce.com",
        email: "hr@tokokitacommerce.com",
        phone: "0215556677",
        foundedYear: 2015,
        companySize: "LARGE",
        companyType: "PRIVATE",
        industryType: "E_COMMERCE",
        status: "ACTIVE",
        verified: true,
        active: true,
        ownerId: 7,
        socialLinks: [
          {
            platform: "LINKEDIN",
            url: "https://linkedin.com/company/toko-kita-commerce",
          },
          {
            platform: "INSTAGRAM",
            url: "https://instagram.com/tokokitacommerce",
          },
          {
            platform: "WEBSITE",
            url: "https://www.tokokitacommerce.com",
          },
        ],
        createdAt: "2026-09-21T06:10:13.036633Z",
        updatedAt: "2026-09-21T06:12:58.220344Z",
      },
      employerId: 7,
      category: {
        id: 2,
        name: "Frontend Development",
        slug: "frontend-development",
        description: "Kategori yang mencakup pengembangan antarmuka pengguna (UI) menggunakan teknologi web seperti HTML, CSS, JavaScript, dan framework modern seperti React, Vue, dan Angular.",
        iconUrl: "https://api.iconify.design/tabler/code.svg",
        active: true,
        parentId: 1,
        parentName: "Software Development",
        subCategories: [],
        createdAt: "2026-09-25T00:17:36.005262Z",
      },
      skills: [
        {
          id: 13,
          name: "Next.js",
          slug: "next-js",
          category: "FRAMEWORK",
          active: true,
        },
        {
          id: 3,
          name: "React",
          slug: "react",
          category: "FRAMEWORK",
          active: true,
        },
        {
          id: 2,
          name: "TypeScript",
          slug: "typescript",
          category: "PROGRAMMING_LANGUAGE",
          active: true,
        },
        {
          id: 15,
          name: "Tailwind CSS",
          slug: "tailwind-css",
          category: "FRAMEWORK",
          active: true,
        },
      ],
      tags: [
        {
          id: 4,
          name: "Work Life Balance",
          slug: "work-life-balance",
          active: true,
        },
        {
          id: 1,
          name: "Remote Friendly",
          slug: "remote-friendly",
          active: true,
        },
      ],
      address: "Jl. Letjen S. Parman Kav. 28, APL Tower Lt. 18",
      city: "Jakarta Barat",
      state: "DKI Jakarta",
      country: "Indonesia",
      zipCode: "11470",
      minSalary: 17000000,
      maxSalary: 27000000,
      currency: "IDR",
      salaryNegotiable: true,
      salaryDisclosed: true,
      jobType: "FULL_TIME",
      workMode: "HYBRID",
      experienceLevel: "MID_LEVEL",
      status: "OPEN",
      openings: 3,
      applicationDeadline: "2026-11-30",
      expiresAt: "2026-12-30",
      active: true,
      viewCount: 195,
      applicationCount: 77,
      createdAt: "2026-09-25T05:40:15.153565Z",
      updatedAt: "2026-09-25T05:42:15.240665Z",
      publishedAt: "2026-09-25T05:42:15.240665Z",
      closedAt: null,
    },
    savedAt: "2026-09-30T14:02:11.418207Z",
  },
  {
    id: 4,
    candidate: {
      id: 1,
      fullName: "jokowi",
      email: "jokowi@gmail.com",
      phone: "021222333124",
      profileImage: null,
      role: "ROLE_EMPLOYER",
      status: "ACTIVE",
      lastLogin: "2026-07-29T23:49:36.189082Z",
      createdAt: "2026-07-29T23:49:36.268324Z",
    },
    job: {
      id: 23,
      title: "Data Scientist",
      description: "Kembangkan model prediksi permintaan dan rekomendasi produk untuk klien ritel. Kamu akan terlibat dari eksplorasi data hingga presentasi hasil kepada klien.",
      requirements: "- Minimal 2 tahun pengalaman sebagai Data Scientist\n- Menguasai Python, pandas, dan scikit-learn\n- Memahami statistik dan eksperimen (A/B testing)\n- Pengalaman dengan time series forecasting\n- Kemampuan presentasi yang baik",
      responsibilities: "- Membangun model forecasting dan rekomendasi\n- Melakukan analisis eksploratif pada data klien\n- Mempresentasikan temuan kepada stakeholder\n- Berkolaborasi dengan Data Engineer untuk produksi model",
      benefits: "- Gaji kompetitif dan bonus proyek\n- Hybrid 2 hari WFO\n- Asuransi kesehatan\n- Akses dataset dan komputasi cloud untuk riset",
      company: {
        id: 8,
        name: "PT Data Cerdas Analitika",
        slug: "pt-data-cerdas-analitika",
        tagline: "Mengubah data menjadi keputusan",
        description: "PT Data Cerdas Analitika menyediakan solusi data platform, business intelligence, dan AI untuk perusahaan ritel dan perbankan di Asia Tenggara.",
        logoUrl: "https://ui-avatars.com/api/?name=Data+Cerdas+Analitika&background=0891B2&color=fff&size=256&bold=true",
        coverImageUrl: "https://picsum.photos/seed/data-cerdas-analitika/1200/400",
        website: "https://www.datacerdasanalitika.com",
        email: "hr@datacerdasanalitika.com",
        phone: "0219988776",
        foundedYear: 2017,
        companySize: "MEDIUM",
        companyType: "PRIVATE",
        industryType: "TECHNOLOGY",
        status: "ACTIVE",
        verified: true,
        active: true,
        ownerId: 9,
        socialLinks: [
          {
            platform: "LINKEDIN",
            url: "https://linkedin.com/company/data-cerdas-analitika",
          },
          {
            platform: "INSTAGRAM",
            url: "https://instagram.com/datacerdasanalitika",
          },
          {
            platform: "WEBSITE",
            url: "https://www.datacerdasanalitika.com",
          },
        ],
        createdAt: "2026-09-23T08:10:13.036633Z",
        updatedAt: "2026-09-23T08:12:58.220344Z",
      },
      employerId: 9,
      category: {
        id: 7,
        name: "Data & AI",
        slug: "data-ai",
        description: "Pekerjaan di bidang data engineering, data analysis, data science, dan machine learning.",
        iconUrl: "https://api.iconify.design/tabler/brain.svg",
        active: true,
        parentId: 10,
        parentName: "Data & Analytics",
        subCategories: [],
        createdAt: "2026-09-25T00:22:36.005262Z",
      },
      skills: [
        {
          id: 18,
          name: "Python",
          slug: "python",
          category: "PROGRAMMING_LANGUAGE",
          active: true,
        },
        {
          id: 31,
          name: "TensorFlow",
          slug: "tensorflow",
          category: "FRAMEWORK",
          active: true,
        },
        {
          id: 30,
          name: "SQL",
          slug: "sql",
          category: "PROGRAMMING_LANGUAGE",
          active: true,
        },
      ],
      tags: [
        {
          id: 4,
          name: "Work Life Balance",
          slug: "work-life-balance",
          active: true,
        },
      ],
      address: "Jl. M.H. Thamrin No. 1, Menara BCA Lt. 45",
      city: "Jakarta Pusat",
      state: "DKI Jakarta",
      country: "Indonesia",
      zipCode: "10310",
      minSalary: 18000000,
      maxSalary: 28000000,
      currency: "IDR",
      salaryNegotiable: false,
      salaryDisclosed: true,
      jobType: "FULL_TIME",
      workMode: "HYBRID",
      experienceLevel: "MID_LEVEL",
      status: "OPEN",
      openings: 1,
      applicationDeadline: "2026-12-03",
      expiresAt: "2027-01-03",
      active: true,
      viewCount: 1291,
      applicationCount: 21,
      createdAt: "2026-09-25T09:00:59.182133Z",
      updatedAt: "2026-09-25T09:02:59.262353Z",
      publishedAt: "2026-09-25T09:02:59.262353Z",
      closedAt: null,
    },
    savedAt: "2026-09-30T15:27:45.093816Z",
  },
];
