export const applications = [
  {
    id: 1,
    candidate: {
      id: 1,
      fullName: "duarrrr",
      email: "duarrrr28@gmail.com",
      phone: "021222333122",
      profileImage: null,
      role: "ROLE_JOB_SEEKER",
      status: "ACTIVE",
      lastLogin: "2026-09-25T00:04:15.500734Z",
      createdAt: "2026-09-25T00:04:15.921817Z",
    },
    employerId: 2,
    job: {
      id: 1,
      title: "Senior Backend Engineer",
      description:
        "Kami mencari Senior Backend Engineer untuk memperkuat tim Payment. Kamu akan merancang dan membangun layanan microservices yang menangani lebih dari 2 juta transaksi per hari, memimpin migrasi dari monolit ke arsitektur event-driven, serta membimbing engineer junior di tim.",
      requirements:
        "- Minimal 5 tahun pengalaman backend development dengan Java\n- Penguasaan mendalam Spring Boot, JPA/Hibernate, dan PostgreSQL\n- Pengalaman membangun sistem terdistribusi dengan Kafka atau message broker sejenis\n- Memahami praktik CI/CD, Docker, dan Kubernetes\n- Mampu berkomunikasi teknis dalam bahasa Inggris",
      responsibilities:
        "- Merancang dan mengimplementasikan REST API yang scalable\n- Melakukan code review dan menjaga kualitas kode tim\n- Berkolaborasi dengan tim Product dan Frontend\n- Memantau performa layanan dan melakukan optimasi\n- Mentoring 2-3 engineer junior",
      benefits:
        "- Gaji kompetitif dengan review tahunan\n- BPJS Kesehatan dan asuransi swasta untuk karyawan dan keluarga\n- Hybrid 3 hari WFO di Jakarta Selatan\n- Budget pengembangan diri Rp 15.000.000 per tahun\n- 16 hari cuti tahunan di luar cuti bersama",
      company: {
        id: 1,
        name: "PT Teknologi Nusantara",
        slug: "pt-teknologi-nusantara",
        tagline: "Building the future of digital hiring",
        description:
          "PT Teknologi Nusantara adalah perusahaan teknologi yang fokus pada pengembangan platform job portal berbasis AI untuk mempertemukan talenta terbaik dengan perusahaan di Indonesia.",
        logoUrl:
          "https://ui-avatars.com/api/?name=Teknologi+Nusantara&background=7C3AED&color=fff&size=256&bold=true",
        coverImageUrl:
          "https://picsum.photos/seed/teknologi-nusantara/1200/400",
        website: "https://www.teknologinusantara.com",
        email: "hr@teknologinusantara.com",
        phone: "0211234567",
        foundedYear: 2018,
        companySize: "MEDIUM",
        companyType: "PRIVATE",
        industryType: "TECHNOLOGY",
        status: "ACTIVE",
        verified: true,
        active: true,
        ownerId: 2,
        socialLinks: [
          {
            platform: "LINKEDIN",
            url: "https://linkedin.com/company/teknologi-nusantara",
          },
          {
            platform: "INSTAGRAM",
            url: "https://instagram.com/teknologinusantara",
          },
          {
            platform: "WEBSITE",
            url: "https://www.teknologinusantara.com",
          },
        ],
        createdAt: "2026-09-25T00:10:13.036633Z",
        updatedAt: "2026-09-25T00:12:58.220344Z",
      },
      employerId: 2,
      category: {
        id: 4,
        name: "Backend Development",
        slug: "backend-development",
        description:
          "Pekerjaan yang berfokus pada pengembangan sisi server, logika bisnis, RESTful API, dan manajemen database menggunakan teknologi seperti Java, Node.js, Python, dan Spring Boot.",
        iconUrl: "https://cdn.johanwork.com/icons/backend-development.svg",
        active: true,
        parentId: 1,
        parentName: "Software Development",
        subCategories: [],
        createdAt: "2026-09-25T00:19:42.731695Z",
      },
      skills: [
        {
          id: 2,
          name: "TypeScript",
          slug: "typescript",
          category: "PROGRAMMING_LANGUAGE",
          active: true,
        },
        {
          id: 7,
          name: "AWS",
          slug: "aws",
          category: "CLOUD_PLATFORM",
          active: true,
        },
        {
          id: 1,
          name: "Java",
          slug: "java",
          category: "PROGRAMMING_LANGUAGE",
          active: true,
        },
        {
          id: 6,
          name: "Redis",
          slug: "redis",
          category: "DATABASE",
          active: true,
        },
        {
          id: 4,
          name: "Spring Boot",
          slug: "spring-boot",
          category: "FRAMEWORK",
          active: true,
        },
        {
          id: 5,
          name: "PostgreSQL",
          slug: "postgresql",
          category: "DATABASE",
          active: true,
        },
      ],
      tags: [
        {
          id: 2,
          name: "Urgent Hiring",
          slug: "urgent-hiring",
          active: true,
        },
        {
          id: 4,
          name: "Work Life Balance",
          slug: "work-life-balance",
          active: true,
        },
        {
          id: 1,
          name: "Remote Friendly",
          slug: "remote-friendly",
          active: true,
        },
      ],
      address: "Jl. Prof. Dr. Satrio No. 164, Menara Standard Chartered Lt. 21",
      city: "Jakarta Selatan",
      state: "DKI Jakarta",
      country: "Indonesia",
      zipCode: "12930",
      minSalary: 25000000.0,
      maxSalary: 40000000.0,
      currency: null,
      salaryNegotiable: null,
      salaryDisclosed: null,
      jobType: "FULL_TIME",
      workMode: "HYBRID",
      experienceLevel: "SENIOR_LEVEL",
      status: "OPEN",
      openings: 5,
      applicationDeadline: "2026-11-30",
      expiresAt: "2026-12-31",
      active: true,
      viewCount: null,
      applicationCount: null,
      createdAt: "2026-09-25T00:35:17.227688Z",
      updatedAt: "2026-09-25T00:38:19.099148Z",
      publishedAt: "2026-09-25T00:38:19.022336Z",
      closedAt: null,
    },
    company: {
      id: 1,
      name: "PT Teknologi Nusantara",
      slug: "pt-teknologi-nusantara",
      tagline: "Building the future of digital hiring",
      description:
        "PT Teknologi Nusantara adalah perusahaan teknologi yang fokus pada pengembangan platform job portal berbasis AI untuk mempertemukan talenta terbaik dengan perusahaan di Indonesia.",
      logoUrl:
        "https://ui-avatars.com/api/?name=Teknologi+Nusantara&background=7C3AED&color=fff&size=256&bold=true",
      coverImageUrl: "https://picsum.photos/seed/teknologi-nusantara/1200/400",
      website: "https://www.teknologinusantara.com",
      email: "hr@teknologinusantara.com",
      phone: "0211234567",
      foundedYear: 2018,
      companySize: "MEDIUM",
      companyType: "PRIVATE",
      industryType: "TECHNOLOGY",
      status: "ACTIVE",
      verified: true,
      active: true,
      ownerId: 2,
      socialLinks: [
        {
          platform: "LINKEDIN",
          url: "https://linkedin.com/company/teknologi-nusantara",
        },
        {
          platform: "INSTAGRAM",
          url: "https://instagram.com/teknologinusantara",
        },
        {
          platform: "WEBSITE",
          url: "https://www.teknologinusantara.com",
        },
      ],
      createdAt: "2026-09-25T00:10:13.036633Z",
      updatedAt: "2026-09-25T00:12:58.220344Z",
    },
    status: "REVIEWING",
    resumeId: 1,
    coverLetter:
      "Kepada Tim Rekrutmen,\n\nSaya mengajukan diri untuk posisi Senior Backend Engineer. Selama enam tahun terakhir saya membangun layanan backend berskala besar, tiga tahun di antaranya menangani sistem pembayaran di Tokopedia yang memproses dua juta transaksi per hari.\n\nDua hal yang saya bawa dan relevan langsung dengan kebutuhan di deskripsi lowongan:\n\nPertama, pengalaman migrasi monolit ke arsitektur event-driven. Saya memimpin pemecahan modul pembayaran menjadi empat service terpisah dengan Kafka sebagai tulang punggung komunikasi, tanpa downtime pada jam operasional. Proses ini menuntut perancangan skema event, penanganan idempotensi, dan strategi rollback yang matang.\n\nKedua, optimasi performa yang terukur. Saya menurunkan p99 latency checkout dari 1.2 detik menjadi 380 milidetik melalui caching Redis berlapis dan perbaikan query yang sebelumnya menimbulkan N+1. Perbaikan ini saya dokumentasikan dan jadikan standar review tim.\n\nSaat ini saya juga sedang menempuh Magister Teknik Informatika di ITB dengan konsentrasi Distributed Systems, yang memperkuat dasar teori dari pekerjaan sehari-hari saya.\n\nSaya tertarik pada posisi ini karena skala transaksi dan tantangan konsistensi data yang disebutkan dalam deskripsi pekerjaan. Saya terbuka untuk membahas lebih lanjut kapan pun.\n\nHormat saya,\nDuarrrr Doe Maklen",
    expectedSalary: 38000000.0,
    availableFrom: "2026-11-01",
    isStarred: false,
    notes: [
      {
        id: 1,
        addByUserId: 2,
        content:
          "Ekspektasi gaji Rp 38.000.000, masih dalam budget (range 25-40 juta). Available from 1 Nov 2026, sesuai target onboarding kami. Perlu dikonfirmasi apakah jadwal kuliah S2 di ITB mengganggu jam kerja.",
        createdAt: "2026-09-25T01:42:09.576449Z",
      },
    ],
    withdrawnAt: null,
    withdrawnReason: null,
    appliedAt: "2026-09-25T01:37:42.998736Z",
    updatedAt: "2026-09-25T01:45:09.275346Z",
  },
  {
    id: 2,
    candidate: {
      id: 1,
      fullName: "duarrrr",
      email: "duarrrr28@gmail.com",
      phone: "021222333122",
      profileImage: null,
      role: "ROLE_JOB_SEEKER",
      status: "ACTIVE",
      lastLogin: "2026-09-25T00:04:15.500734Z",
      createdAt: "2026-09-25T00:04:15.921817Z",
    },
    employerId: 4,
    job: {
      id: 27,
      title: "Backend Engineer (Node.js)",
      description:
        "Kembangkan layanan backend untuk sistem rekam medis elektronik dan integrasi SATUSEHAT. Kamu akan membangun API yang aman dan sesuai regulasi data kesehatan.",
      requirements:
        "- Minimal 2 tahun pengalaman backend development dengan Node.js\n- Menguasai TypeScript dan framework seperti NestJS atau Express\n- Pengalaman dengan PostgreSQL atau MongoDB\n- Memahami keamanan data dan autentikasi (OAuth2, JWT)\n- Nilai tambah: pengalaman dengan standar HL7 FHIR",
      responsibilities:
        "- Membangun API rekam medis elektronik\n- Mengintegrasikan sistem dengan platform SATUSEHAT\n- Menjaga keamanan dan privasi data pasien\n- Menulis unit test dan dokumentasi API",
      benefits:
        "- Gaji kompetitif\n- Konsultasi dokter gratis untuk karyawan dan keluarga\n- Hybrid 2 hari WFO di Bandung\n- Budget belajar tahunan",
      company: {
        id: 3,
        name: "PT Sehat Digital Sejahtera",
        slug: "pt-sehat-digital-sejahtera",
        tagline: "Akses kesehatan dalam genggaman",
        description:
          "PT Sehat Digital Sejahtera mengembangkan aplikasi telemedicine dan manajemen rekam medis elektronik yang terhubung dengan lebih dari 1.200 fasilitas kesehatan.",
        logoUrl:
          "https://ui-avatars.com/api/?name=Sehat+Digital+Sejahtera&background=16A34A&color=fff&size=256&bold=true",
        coverImageUrl:
          "https://picsum.photos/seed/sehat-digital-sejahtera/1200/400",
        website: "https://www.sehatdigitalsejahtera.com",
        email: "hr@sehatdigitalsejahtera.com",
        phone: "0224567890",
        foundedYear: 2019,
        companySize: "MEDIUM",
        companyType: "PRIVATE",
        industryType: "HEALTHCARE",
        status: "ACTIVE",
        verified: true,
        active: true,
        ownerId: 4,
        socialLinks: [
          {
            platform: "LINKEDIN",
            url: "https://linkedin.com/company/sehat-digital-sejahtera",
          },
          {
            platform: "INSTAGRAM",
            url: "https://instagram.com/sehatdigitalsejahtera",
          },
          {
            platform: "WEBSITE",
            url: "https://www.sehatdigitalsejahtera.com",
          },
        ],
        createdAt: "2026-09-23T03:10:13.036633Z",
        updatedAt: "2026-09-23T03:12:58.220344Z",
      },
      employerId: 4,
      category: {
        id: 4,
        name: "Backend Development",
        slug: "backend-development",
        description:
          "Pekerjaan yang berfokus pada pengembangan sisi server, logika bisnis, RESTful API, dan manajemen database menggunakan teknologi seperti Java, Node.js, Python, dan Spring Boot.",
        iconUrl: "https://api.iconify.design/tabler/server.svg",
        active: true,
        parentId: 1,
        parentName: "Software Development",
        subCategories: [],
        createdAt: "2026-09-25T00:19:36.005262Z",
      },
      skills: [
        {
          id: 16,
          name: "Node.js",
          slug: "node-js",
          category: "FRAMEWORK",
          active: true,
        },
        {
          id: 2,
          name: "TypeScript",
          slug: "typescript",
          category: "PROGRAMMING_LANGUAGE",
          active: true,
        },
        {
          id: 5,
          name: "PostgreSQL",
          slug: "postgresql",
          category: "DATABASE",
          active: true,
        },
        {
          id: 23,
          name: "MongoDB",
          slug: "mongodb",
          category: "DATABASE",
          active: true,
        },
      ],
      tags: [
        {
          id: 4,
          name: "Work Life Balance",
          slug: "work-life-balance",
          active: true,
        },
        {
          id: 1,
          name: "Remote Friendly",
          slug: "remote-friendly",
          active: true,
        },
      ],
      address: "Jl. Asia Afrika No. 133-137, Gedung Graha Sehat Lt. 5",
      city: "Bandung",
      state: "Jawa Barat",
      country: "Indonesia",
      zipCode: "40112",
      minSalary: 13000000,
      maxSalary: 20000000,
      currency: "IDR",
      salaryNegotiable: true,
      salaryDisclosed: true,
      jobType: "FULL_TIME",
      workMode: "HYBRID",
      experienceLevel: "MID_LEVEL",
      status: "OPEN",
      openings: 2,
      applicationDeadline: "2026-12-02",
      expiresAt: "2027-01-02",
      active: true,
      viewCount: 1839,
      applicationCount: 113,
      createdAt: "2026-09-25T10:40:51.196417Z",
      updatedAt: "2026-09-25T10:42:51.273197Z",
      publishedAt: "2026-09-25T10:42:51.273197Z",
      closedAt: null,
    },
    company: {
      id: 3,
      name: "PT Sehat Digital Sejahtera",
      slug: "pt-sehat-digital-sejahtera",
      tagline: "Akses kesehatan dalam genggaman",
      description:
        "PT Sehat Digital Sejahtera mengembangkan aplikasi telemedicine dan manajemen rekam medis elektronik yang terhubung dengan lebih dari 1.200 fasilitas kesehatan.",
      logoUrl:
        "https://ui-avatars.com/api/?name=Sehat+Digital+Sejahtera&background=16A34A&color=fff&size=256&bold=true",
      coverImageUrl:
        "https://picsum.photos/seed/sehat-digital-sejahtera/1200/400",
      website: "https://www.sehatdigitalsejahtera.com",
      email: "hr@sehatdigitalsejahtera.com",
      phone: "0224567890",
      foundedYear: 2019,
      companySize: "MEDIUM",
      companyType: "PRIVATE",
      industryType: "HEALTHCARE",
      status: "ACTIVE",
      verified: true,
      active: true,
      ownerId: 4,
      socialLinks: [
        {
          platform: "LINKEDIN",
          url: "https://linkedin.com/company/sehat-digital-sejahtera",
        },
        {
          platform: "INSTAGRAM",
          url: "https://instagram.com/sehatdigitalsejahtera",
        },
        {
          platform: "WEBSITE",
          url: "https://www.sehatdigitalsejahtera.com",
        },
      ],
      createdAt: "2026-09-23T03:10:13.036633Z",
      updatedAt: "2026-09-23T03:12:58.220344Z",
    },
    status: "INTERVIEW_SCHEDULED",
    resumeId: 1,
    coverLetter:
      "Kepada Tim Rekrutmen PT Sehat Digital Sejahtera,\n\nSaya ingin melamar posisi Backend Engineer (Node.js). Enam tahun terakhir saya membangun layanan backend berskala besar, dan selain Java saya aktif menulis service Node.js dengan TypeScript untuk kebutuhan internal tim.\n\nPengalaman saya menangani data transaksi yang sensitif membuat saya terbiasa dengan praktik keamanan data, audit log, dan konsistensi transaksi, hal yang menurut saya sangat relevan untuk platform kesehatan yang mengelola data pasien.\n\nSaya tertarik bergabung karena misi PT Sehat Digital Sejahtera untuk memperluas akses layanan kesehatan digital. Saya siap berdiskusi lebih lanjut kapan pun.\n\nHormat saya,\nDuarrrr Doe Maklen",
    expectedSalary: 19000000,
    availableFrom: "2026-11-15",
    isStarred: true,
    notes: [
      {
        id: 2,
        addByUserId: 4,
        content:
          "Profil kuat, pengalaman sistem pembayaran relevan untuk modul billing kami. Ekspektasi gaji Rp 19.000.000 masih dalam range 13-20 juta. Lanjut ke interview teknis.",
        createdAt: "2026-09-26T03:15:22.104512Z",
      },
      {
        id: 3,
        addByUserId: 4,
        content:
          "Interview teknis dijadwalkan Kamis, 2 Oktober 2026 pukul 10.00 WIB via Google Meet. Fokus: desain API dan pengalaman Node.js di production.",
        createdAt: "2026-09-27T08:40:10.552301Z",
      },
    ],
    withdrawnAt: null,
    withdrawnReason: null,
    appliedAt: "2026-09-25T09:12:33.418270Z",
    updatedAt: "2026-09-27T08:40:10.552301Z",
  },
  {
    id: 3,
    candidate: {
      id: 1,
      fullName: "duarrrr",
      email: "duarrrr28@gmail.com",
      phone: "021222333122",
      profileImage: null,
      role: "ROLE_JOB_SEEKER",
      status: "ACTIVE",
      lastLogin: "2026-09-25T00:04:15.500734Z",
      createdAt: "2026-09-25T00:04:15.921817Z",
    },
    employerId: 3,
    job: {
      id: 3,
      title: "Backend Engineer (Golang)",
      description:
        "Bergabunglah dengan tim Core Payment untuk membangun layanan pemrosesan transaksi berlatensi rendah. Kamu akan mengembangkan API yang dipakai ribuan merchant setiap harinya dengan target uptime 99,99%.",
      requirements:
        "- Minimal 3 tahun pengalaman backend development\n- Menguasai Go dan konsep concurrency (goroutine, channel)\n- Pengalaman dengan PostgreSQL dan Redis\n- Memahami prinsip idempotency dan konsistensi data pada sistem pembayaran\n- Terbiasa menulis unit test dan integration test",
      responsibilities:
        "- Membangun dan memelihara layanan pembayaran berbasis Go\n- Mengoptimalkan query database dan caching\n- Menangani insiden produksi bersama tim SRE\n- Menulis dokumentasi teknis dan API contract",
      benefits:
        "- Gaji kompetitif dan bonus tahunan berdasarkan kinerja\n- Asuransi kesehatan swasta termasuk rawat gigi dan kacamata\n- Hybrid 2 hari WFO\n- Makan siang gratis setiap hari kantor\n- Program kepemilikan saham karyawan (ESOP)",
      company: {
        id: 2,
        name: "PT Bayar Cepat Indonesia",
        slug: "pt-bayar-cepat-indonesia",
        tagline: "Pembayaran digital untuk semua",
        description:
          "PT Bayar Cepat Indonesia adalah perusahaan fintech penyedia layanan payment gateway dan dompet digital yang melayani lebih dari 40.000 merchant di seluruh Indonesia.",
        logoUrl:
          "https://ui-avatars.com/api/?name=Bayar+Cepat+Indonesia&background=2563EB&color=fff&size=256&bold=true",
        coverImageUrl:
          "https://picsum.photos/seed/bayar-cepat-indonesia/1200/400",
        website: "https://www.bayarcepatindonesia.com",
        email: "hr@bayarcepatindonesia.com",
        phone: "0217654321",
        foundedYear: 2016,
        companySize: "LARGE",
        companyType: "PRIVATE",
        industryType: "FINANCE",
        status: "ACTIVE",
        verified: true,
        active: true,
        ownerId: 3,
        socialLinks: [
          {
            platform: "LINKEDIN",
            url: "https://linkedin.com/company/bayar-cepat-indonesia",
          },
          {
            platform: "INSTAGRAM",
            url: "https://instagram.com/bayarcepatindonesia",
          },
          {
            platform: "WEBSITE",
            url: "https://www.bayarcepatindonesia.com",
          },
        ],
        createdAt: "2026-09-22T02:10:13.036633Z",
        updatedAt: "2026-09-22T02:12:58.220344Z",
      },
      employerId: 3,
      category: {
        id: 4,
        name: "Backend Development",
        slug: "backend-development",
        description:
          "Pekerjaan yang berfokus pada pengembangan sisi server, logika bisnis, RESTful API, dan manajemen database menggunakan teknologi seperti Java, Node.js, Python, dan Spring Boot.",
        iconUrl: "https://api.iconify.design/tabler/server.svg",
        active: true,
        parentId: 1,
        parentName: "Software Development",
        subCategories: [],
        createdAt: "2026-09-25T00:19:36.005262Z",
      },
      skills: [
        {
          id: 17,
          name: "Go",
          slug: "go",
          category: "PROGRAMMING_LANGUAGE",
          active: true,
        },
        {
          id: 5,
          name: "PostgreSQL",
          slug: "postgresql",
          category: "DATABASE",
          active: true,
        },
        {
          id: 6,
          name: "Redis",
          slug: "redis",
          category: "DATABASE",
          active: true,
        },
        {
          id: 8,
          name: "Docker",
          slug: "docker",
          category: "TOOL",
          active: true,
        },
        {
          id: 24,
          name: "Kafka",
          slug: "kafka",
          category: "TOOL",
          active: true,
        },
      ],
      tags: [
        {
          id: 6,
          name: "Stock Options",
          slug: "stock-options",
          active: true,
        },
        {
          id: 4,
          name: "Work Life Balance",
          slug: "work-life-balance",
          active: true,
        },
      ],
      address: "Jl. Jend. Sudirman Kav. 52-53, Equity Tower Lt. 30",
      city: "Jakarta Selatan",
      state: "DKI Jakarta",
      country: "Indonesia",
      zipCode: "12190",
      minSalary: 18000000,
      maxSalary: 28000000,
      currency: "IDR",
      salaryNegotiable: true,
      salaryDisclosed: true,
      jobType: "FULL_TIME",
      workMode: "HYBRID",
      experienceLevel: "MID_LEVEL",
      status: "OPEN",
      openings: 3,
      applicationDeadline: "2026-11-20",
      expiresAt: "2026-12-20",
      active: true,
      viewCount: 451,
      applicationCount: 41,
      createdAt: "2026-09-25T00:40:39.110713Z",
      updatedAt: "2026-09-25T00:42:39.208133Z",
      publishedAt: "2026-09-25T00:42:39.208133Z",
      closedAt: null,
    },
    company: {
      id: 2,
      name: "PT Bayar Cepat Indonesia",
      slug: "pt-bayar-cepat-indonesia",
      tagline: "Pembayaran digital untuk semua",
      description:
        "PT Bayar Cepat Indonesia adalah perusahaan fintech penyedia layanan payment gateway dan dompet digital yang melayani lebih dari 40.000 merchant di seluruh Indonesia.",
      logoUrl:
        "https://ui-avatars.com/api/?name=Bayar+Cepat+Indonesia&background=2563EB&color=fff&size=256&bold=true",
      coverImageUrl:
        "https://picsum.photos/seed/bayar-cepat-indonesia/1200/400",
      website: "https://www.bayarcepatindonesia.com",
      email: "hr@bayarcepatindonesia.com",
      phone: "0217654321",
      foundedYear: 2016,
      companySize: "LARGE",
      companyType: "PRIVATE",
      industryType: "FINANCE",
      status: "ACTIVE",
      verified: true,
      active: true,
      ownerId: 3,
      socialLinks: [
        {
          platform: "LINKEDIN",
          url: "https://linkedin.com/company/bayar-cepat-indonesia",
        },
        {
          platform: "INSTAGRAM",
          url: "https://instagram.com/bayarcepatindonesia",
        },
        {
          platform: "WEBSITE",
          url: "https://www.bayarcepatindonesia.com",
        },
      ],
      createdAt: "2026-09-22T02:10:13.036633Z",
      updatedAt: "2026-09-22T02:12:58.220344Z",
    },
    status: "PENDING",
    resumeId: 1,
    coverLetter:
      "Kepada Tim Rekrutmen PT Bayar Cepat Indonesia,\n\nSaya mengajukan lamaran untuk posisi Backend Engineer (Golang). Saya memiliki pengalaman enam tahun membangun sistem pembayaran, termasuk menurunkan p99 latency checkout sebesar 68% dan memimpin migrasi ke arsitektur event-driven berbasis Kafka.\n\nWalaupun bahasa utama saya selama ini adalah Java, dalam satu tahun terakhir saya menulis beberapa service internal dengan Golang, termasuk worker rekonsiliasi transaksi harian. Saya percaya pengalaman domain pembayaran saya dapat langsung memberi nilai bagi tim.\n\nTerima kasih atas waktu dan pertimbangannya.\n\nHormat saya,\nDuarrrr Doe Maklen",
    expectedSalary: 26000000,
    availableFrom: "2026-12-01",
    isStarred: false,
    notes: [],
    withdrawnAt: "2026-09-28T02:05:47.331904Z",
    withdrawnReason: "Sudah menerima tawaran dari perusahaan lain.",
    appliedAt: "2026-09-25T11:48:02.775619Z",
    updatedAt: "2026-09-28T02:05:47.331904Z",
  },
];
