export const recent = [
  {
    id: 1,
    candidate: {
      id: 1,
      fullName: "Duarrr Wilcom",
      email: "duarrrr28@gmail.com",
      phone: "021222333122",
      profileImage: null,
      role: "ROLE_JOB_SEEKER",
      status: "ACTIVE",
      lastLogin: "2026-09-25T00:04:15.500734Z",
      createdAt: "2026-09-25T00:04:15.921817Z",
    },
    employerId: 2,
    job: {
      id: 1,
      title: "Senior Backend Engineer",
      description:
        "Kami mencari Senior Backend Engineer untuk memperkuat tim Payment. Kamu akan merancang dan membangun layanan microservices yang menangani lebih dari 2 juta transaksi per hari, memimpin migrasi dari monolit ke arsitektur event-driven, serta membimbing engineer junior di tim.",
      requirements:
        "- Minimal 5 tahun pengalaman backend development dengan Java\n- Penguasaan mendalam Spring Boot, JPA/Hibernate, dan PostgreSQL\n- Pengalaman membangun sistem terdistribusi dengan Kafka atau message broker sejenis\n- Memahami praktik CI/CD, Docker, dan Kubernetes\n- Mampu berkomunikasi teknis dalam bahasa Inggris",
      responsibilities:
        "- Merancang dan mengimplementasikan REST API yang scalable\n- Melakukan code review dan menjaga kualitas kode tim\n- Berkolaborasi dengan tim Product dan Frontend\n- Memantau performa layanan dan melakukan optimasi\n- Mentoring 2-3 engineer junior",
      benefits:
        "- Gaji kompetitif dengan review tahunan\n- BPJS Kesehatan dan asuransi swasta untuk karyawan dan keluarga\n- Hybrid 3 hari WFO di Jakarta Selatan\n- Budget pengembangan diri Rp 15.000.000 per tahun\n- 16 hari cuti tahunan di luar cuti bersama",
      company: {
        id: 1,
        name: "PT Teknologi Nusantara",
        slug: "pt-teknologi-nusantara",
        tagline: "Building the future of digital hiring",
        description:
          "PT Teknologi Nusantara adalah perusahaan teknologi yang fokus pada pengembangan platform job portal berbasis AI untuk mempertemukan talenta terbaik dengan perusahaan di Indonesia.",
        logoUrl:
          "https://ui-avatars.com/api/?name=Teknologi+Nusantara&background=7C3AED&color=fff&size=256&bold=true",
        coverImageUrl:
          "https://picsum.photos/seed/teknologi-nusantara/1200/400",
        website: "https://www.teknologinusantara.com",
        email: "hr@teknologinusantara.com",
        phone: "0211234567",
        foundedYear: 2018,
        companySize: "MEDIUM",
        companyType: "PRIVATE",
        industryType: "TECHNOLOGY",
        status: "ACTIVE",
        verified: true,
        active: true,
        ownerId: 2,
        socialLinks: [
          {
            platform: "LINKEDIN",
            url: "https://linkedin.com/company/teknologi-nusantara",
          },
          {
            platform: "INSTAGRAM",
            url: "https://instagram.com/teknologinusantara",
          },
          {
            platform: "WEBSITE",
            url: "https://www.teknologinusantara.com",
          },
        ],
        createdAt: "2026-09-25T00:10:13.036633Z",
        updatedAt: "2026-09-25T00:12:58.220344Z",
      },
      employerId: 2,
      category: {
        id: 4,
        name: "Backend Development",
        slug: "backend-development",
        description:
          "Pekerjaan yang berfokus pada pengembangan sisi server, logika bisnis, RESTful API, dan manajemen database menggunakan teknologi seperti Java, Node.js, Python, dan Spring Boot.",
        iconUrl: "https://cdn.johanwork.com/icons/backend-development.svg",
        active: true,
        parentId: 1,
        parentName: "Software Development",
        subCategories: [],
        createdAt: "2026-09-25T00:19:42.731695Z",
      },
      skills: [
        {
          id: 2,
          name: "TypeScript",
          slug: "typescript",
          category: "PROGRAMMING_LANGUAGE",
          active: true,
        },
        {
          id: 7,
          name: "AWS",
          slug: "aws",
          category: "CLOUD_PLATFORM",
          active: true,
        },
        {
          id: 1,
          name: "Java",
          slug: "java",
          category: "PROGRAMMING_LANGUAGE",
          active: true,
        },
        {
          id: 6,
          name: "Redis",
          slug: "redis",
          category: "DATABASE",
          active: true,
        },
        {
          id: 4,
          name: "Spring Boot",
          slug: "spring-boot",
          category: "FRAMEWORK",
          active: true,
        },
        {
          id: 5,
          name: "PostgreSQL",
          slug: "postgresql",
          category: "DATABASE",
          active: true,
        },
      ],
      tags: [
        {
          id: 2,
          name: "Urgent Hiring",
          slug: "urgent-hiring",
          active: true,
        },
        {
          id: 4,
          name: "Work Life Balance",
          slug: "work-life-balance",
          active: true,
        },
        {
          id: 1,
          name: "Remote Friendly",
          slug: "remote-friendly",
          active: true,
        },
      ],
      address: "Jl. Prof. Dr. Satrio No. 164, Menara Standard Chartered Lt. 21",
      city: "Jakarta Selatan",
      state: "DKI Jakarta",
      country: "Indonesia",
      zipCode: "12930",
      minSalary: 25000000.0,
      maxSalary: 40000000.0,
      currency: null,
      salaryNegotiable: null,
      salaryDisclosed: null,
      jobType: "FULL_TIME",
      workMode: "HYBRID",
      experienceLevel: "SENIOR_LEVEL",
      status: "OPEN",
      openings: 5,
      applicationDeadline: "2026-11-30",
      expiresAt: "2026-12-31",
      active: true,
      viewCount: null,
      applicationCount: null,
      createdAt: "2026-09-25T00:35:17.227688Z",
      updatedAt: "2026-09-25T00:38:19.099148Z",
      publishedAt: "2026-09-25T00:38:19.022336Z",
      closedAt: null,
    },
    company: {
      id: 1,
      name: "PT Teknologi Nusantara",
      slug: "pt-teknologi-nusantara",
      tagline: "Building the future of digital hiring",
      description:
        "PT Teknologi Nusantara adalah perusahaan teknologi yang fokus pada pengembangan platform job portal berbasis AI untuk mempertemukan talenta terbaik dengan perusahaan di Indonesia.",
      logoUrl:
        "https://ui-avatars.com/api/?name=Teknologi+Nusantara&background=7C3AED&color=fff&size=256&bold=true",
      coverImageUrl: "https://picsum.photos/seed/teknologi-nusantara/1200/400",
      website: "https://www.teknologinusantara.com",
      email: "hr@teknologinusantara.com",
      phone: "0211234567",
      foundedYear: 2018,
      companySize: "MEDIUM",
      companyType: "PRIVATE",
      industryType: "TECHNOLOGY",
      status: "ACTIVE",
      verified: true,
      active: true,
      ownerId: 2,
      socialLinks: [
        {
          platform: "LINKEDIN",
          url: "https://linkedin.com/company/teknologi-nusantara",
        },
        {
          platform: "INSTAGRAM",
          url: "https://instagram.com/teknologinusantara",
        },
        {
          platform: "WEBSITE",
          url: "https://www.teknologinusantara.com",
        },
      ],
      createdAt: "2026-09-25T00:10:13.036633Z",
      updatedAt: "2026-09-25T00:12:58.220344Z",
    },
    status: "REVIEWING",
    resumeId: 1,
    coverLetter:
      "Kepada Tim Rekrutmen,\n\nSaya mengajukan diri untuk posisi Senior Backend Engineer. Selama enam tahun terakhir saya membangun layanan backend berskala besar, tiga tahun di antaranya menangani sistem pembayaran di Tokopedia yang memproses dua juta transaksi per hari.\n\nDua hal yang saya bawa dan relevan langsung dengan kebutuhan di deskripsi lowongan:\n\nPertama, pengalaman migrasi monolit ke arsitektur event-driven. Saya memimpin pemecahan modul pembayaran menjadi empat service terpisah dengan Kafka sebagai tulang punggung komunikasi, tanpa downtime pada jam operasional. Proses ini menuntut perancangan skema event, penanganan idempotensi, dan strategi rollback yang matang.\n\nKedua, optimasi performa yang terukur. Saya menurunkan p99 latency checkout dari 1.2 detik menjadi 380 milidetik melalui caching Redis berlapis dan perbaikan query yang sebelumnya menimbulkan N+1. Perbaikan ini saya dokumentasikan dan jadikan standar review tim.\n\nSaat ini saya juga sedang menempuh Magister Teknik Informatika di ITB dengan konsentrasi Distributed Systems, yang memperkuat dasar teori dari pekerjaan sehari-hari saya.\n\nSaya tertarik pada posisi ini karena skala transaksi dan tantangan konsistensi data yang disebutkan dalam deskripsi pekerjaan. Saya terbuka untuk membahas lebih lanjut kapan pun.\n\nHormat saya,\nDuarrrr Doe Maklen",
    expectedSalary: 38000000.0,
    availableFrom: "2026-11-01",
    isStarred: false,
    notes: [
      {
        id: 1,
        addByUserId: 2,
        content:
          "Ekspektasi gaji Rp 38.000.000, masih dalam budget (range 25-40 juta). Available from 1 Nov 2026, sesuai target onboarding kami. Perlu dikonfirmasi apakah jadwal kuliah S2 di ITB mengganggu jam kerja.",
        createdAt: "2026-09-25T01:42:09.576449Z",
      },
    ],
    screening: {
      score: 30,
      skillMatchScore: 83,
      experienceMatchScore: 95,
      educationMatchScore: 90,
      matchedSkills: ["Java", "Spring Boot", "PostgreSQL", "Redis", "AWS"],
      missingSkills: ["TypeScript"],
      strengths: [
        "6 tahun pengalaman backend, 3 tahun di sistem pembayaran berskala besar",
        "Memimpin migrasi monolit ke arsitektur event-driven dengan Kafka",
        "Hasil optimasi performa terukur (p99 latency turun 68%)",
      ],
      concerns: [
        "Belum terlihat pengalaman TypeScript",
        "Jadwal kuliah S2 di ITB berpotensi bentrok dengan jam kerja",
      ],
      summary:
        "Kandidat sangat kuat untuk posisi Senior Backend Engineer. Pengalaman di domain pembayaran dan sistem terdistribusi sangat relevan dengan kebutuhan tim Payment. Satu-satunya skill yang belum terpenuhi adalah TypeScript, yang tidak krusial untuk peran ini.",
    },
    withdrawnAt: null,
    withdrawnReason: null,
    appliedAt: "2026-09-25T01:37:42.998736Z",
    updatedAt: "2026-09-25T01:45:09.275346Z",
  },
  {
    id: 2,
    candidate: {
      id: 12,
      fullName: "Andi Pratama",
      email: "andi.pratama@gmail.com",
      phone: "081311224455",
      profileImage: null,
      role: "ROLE_JOB_SEEKER",
      status: "ACTIVE",
      lastLogin: "2026-09-26T06:18:42.337190Z",
      createdAt: "2026-09-18T08:45:03.912644Z",
    },
    employerId: 4,
    job: {
      id: 27,
      title: "Backend Engineer (Node.js)",
      description:
        "Kembangkan layanan backend untuk sistem rekam medis elektronik dan integrasi SATUSEHAT. Kamu akan membangun API yang aman dan sesuai regulasi data kesehatan.",
      requirements:
        "- Minimal 2 tahun pengalaman backend development dengan Node.js\n- Menguasai TypeScript dan framework seperti NestJS atau Express\n- Pengalaman dengan PostgreSQL atau MongoDB\n- Memahami keamanan data dan autentikasi (OAuth2, JWT)\n- Nilai tambah: pengalaman dengan standar HL7 FHIR",
      responsibilities:
        "- Membangun API rekam medis elektronik\n- Mengintegrasikan sistem dengan platform SATUSEHAT\n- Menjaga keamanan dan privasi data pasien\n- Menulis unit test dan dokumentasi API",
      benefits:
        "- Gaji kompetitif\n- Konsultasi dokter gratis untuk karyawan dan keluarga\n- Hybrid 2 hari WFO di Bandung\n- Budget belajar tahunan",
      company: {
        id: 3,
        name: "PT Sehat Digital Sejahtera",
        slug: "pt-sehat-digital-sejahtera",
        tagline: "Akses kesehatan dalam genggaman",
        description:
          "PT Sehat Digital Sejahtera mengembangkan aplikasi telemedicine dan manajemen rekam medis elektronik yang terhubung dengan lebih dari 1.200 fasilitas kesehatan.",
        logoUrl:
          "https://ui-avatars.com/api/?name=Sehat+Digital+Sejahtera&background=16A34A&color=fff&size=256&bold=true",
        coverImageUrl:
          "https://picsum.photos/seed/sehat-digital-sejahtera/1200/400",
        website: "https://www.sehatdigitalsejahtera.com",
        email: "hr@sehatdigitalsejahtera.com",
        phone: "0224567890",
        foundedYear: 2019,
        companySize: "MEDIUM",
        companyType: "PRIVATE",
        industryType: "HEALTHCARE",
        status: "ACTIVE",
        verified: true,
        active: true,
        ownerId: 4,
        socialLinks: [
          {
            platform: "LINKEDIN",
            url: "https://linkedin.com/company/sehat-digital-sejahtera",
          },
          {
            platform: "INSTAGRAM",
            url: "https://instagram.com/sehatdigitalsejahtera",
          },
          {
            platform: "WEBSITE",
            url: "https://www.sehatdigitalsejahtera.com",
          },
        ],
        createdAt: "2026-09-23T03:10:13.036633Z",
        updatedAt: "2026-09-23T03:12:58.220344Z",
      },
      employerId: 4,
      category: {
        id: 4,
        name: "Backend Development",
        slug: "backend-development",
        description:
          "Pekerjaan yang berfokus pada pengembangan sisi server, logika bisnis, RESTful API, dan manajemen database menggunakan teknologi seperti Java, Node.js, Python, dan Spring Boot.",
        iconUrl: "https://api.iconify.design/tabler/server.svg",
        active: true,
        parentId: 1,
        parentName: "Software Development",
        subCategories: [],
        createdAt: "2026-09-25T00:19:36.005262Z",
      },
      skills: [
        {
          id: 16,
          name: "Node.js",
          slug: "node-js",
          category: "FRAMEWORK",
          active: true,
        },
        {
          id: 2,
          name: "TypeScript",
          slug: "typescript",
          category: "PROGRAMMING_LANGUAGE",
          active: true,
        },
        {
          id: 5,
          name: "PostgreSQL",
          slug: "postgresql",
          category: "DATABASE",
          active: true,
        },
        {
          id: 23,
          name: "MongoDB",
          slug: "mongodb",
          category: "DATABASE",
          active: true,
        },
      ],
      tags: [
        {
          id: 4,
          name: "Work Life Balance",
          slug: "work-life-balance",
          active: true,
        },
        {
          id: 1,
          name: "Remote Friendly",
          slug: "remote-friendly",
          active: true,
        },
      ],
      address: "Jl. Asia Afrika No. 133-137, Gedung Graha Sehat Lt. 5",
      city: "Bandung",
      state: "Jawa Barat",
      country: "Indonesia",
      zipCode: "40112",
      minSalary: 13000000,
      maxSalary: 20000000,
      currency: "IDR",
      salaryNegotiable: true,
      salaryDisclosed: true,
      jobType: "FULL_TIME",
      workMode: "HYBRID",
      experienceLevel: "MID_LEVEL",
      status: "OPEN",
      openings: 2,
      applicationDeadline: "2026-12-02",
      expiresAt: "2027-01-02",
      active: true,
      viewCount: 1839,
      applicationCount: 113,
      createdAt: "2026-09-25T10:40:51.196417Z",
      updatedAt: "2026-09-25T10:42:51.273197Z",
      publishedAt: "2026-09-25T10:42:51.273197Z",
      closedAt: null,
    },
    company: {
      id: 3,
      name: "PT Sehat Digital Sejahtera",
      slug: "pt-sehat-digital-sejahtera",
      tagline: "Akses kesehatan dalam genggaman",
      description:
        "PT Sehat Digital Sejahtera mengembangkan aplikasi telemedicine dan manajemen rekam medis elektronik yang terhubung dengan lebih dari 1.200 fasilitas kesehatan.",
      logoUrl:
        "https://ui-avatars.com/api/?name=Sehat+Digital+Sejahtera&background=16A34A&color=fff&size=256&bold=true",
      coverImageUrl:
        "https://picsum.photos/seed/sehat-digital-sejahtera/1200/400",
      website: "https://www.sehatdigitalsejahtera.com",
      email: "hr@sehatdigitalsejahtera.com",
      phone: "0224567890",
      foundedYear: 2019,
      companySize: "MEDIUM",
      companyType: "PRIVATE",
      industryType: "HEALTHCARE",
      status: "ACTIVE",
      verified: true,
      active: true,
      ownerId: 4,
      socialLinks: [
        {
          platform: "LINKEDIN",
          url: "https://linkedin.com/company/sehat-digital-sejahtera",
        },
        {
          platform: "INSTAGRAM",
          url: "https://instagram.com/sehatdigitalsejahtera",
        },
        {
          platform: "WEBSITE",
          url: "https://www.sehatdigitalsejahtera.com",
        },
      ],
      createdAt: "2026-09-23T03:10:13.036633Z",
      updatedAt: "2026-09-23T03:12:58.220344Z",
    },
    status: "INTERVIEW_SCHEDULED",
    resumeId: 1,
    coverLetter:
      "Kepada Tim Rekrutmen PT Sehat Digital Sejahtera,\n\nSaya ingin melamar posisi Backend Engineer (Node.js). Enam tahun terakhir saya membangun layanan backend berskala besar, dan selain Java saya aktif menulis service Node.js dengan TypeScript untuk kebutuhan internal tim.\n\nPengalaman saya menangani data transaksi yang sensitif membuat saya terbiasa dengan praktik keamanan data, audit log, dan konsistensi transaksi, hal yang menurut saya sangat relevan untuk platform kesehatan yang mengelola data pasien.\n\nSaya tertarik bergabung karena misi PT Sehat Digital Sejahtera untuk memperluas akses layanan kesehatan digital. Saya siap berdiskusi lebih lanjut kapan pun.\n\nHormat saya,\nAndi Pratama",
    expectedSalary: 19000000,
    availableFrom: "2026-11-15",
    isStarred: true,
    notes: [
      {
        id: 2,
        addByUserId: 4,
        content:
          "Profil kuat, pengalaman sistem pembayaran relevan untuk modul billing kami. Ekspektasi gaji Rp 19.000.000 masih dalam range 13-20 juta. Lanjut ke interview teknis.",
        createdAt: "2026-09-26T03:15:22.104512Z",
      },
      {
        id: 3,
        addByUserId: 4,
        content:
          "Interview teknis dijadwalkan Kamis, 2 Oktober 2026 pukul 10.00 WIB via Google Meet. Fokus: desain API dan pengalaman Node.js di production.",
        createdAt: "2026-09-27T08:40:10.552301Z",
      },
    ],
    screening: {
      score: 79,
      skillMatchScore: 75,
      experienceMatchScore: 85,
      educationMatchScore: 80,
      matchedSkills: ["Node.js", "TypeScript", "PostgreSQL"],
      missingSkills: ["MongoDB"],
      strengths: [
        "Pengalaman Node.js dan TypeScript di lingkungan production",
        "Terbiasa dengan praktik keamanan data dan audit log",
      ],
      concerns: [
        "Belum ada pengalaman dengan MongoDB",
        "Pengalaman Node.js lebih banyak di service internal, belum di produk utama",
      ],
      summary:
        "Kandidat cocok untuk posisi Backend Engineer (Node.js) dengan fondasi backend yang solid. Perlu digali lebih dalam pada interview teknis terkait pengalaman Node.js di skala produk dan kesiapan mempelajari MongoDB.",
    },
    withdrawnAt: null,
    withdrawnReason: null,
    appliedAt: "2026-09-25T09:12:33.418270Z",
    updatedAt: "2026-09-27T08:40:10.552301Z",
  },
  {
    id: 3,
    candidate: {
      id: 13,
      fullName: "Rina Kurniawati",
      email: "rina.kurniawati@outlook.com",
      phone: "087856781234",
      profileImage: null,
      role: "ROLE_JOB_SEEKER",
      status: "ACTIVE",
      lastLogin: "2026-09-27T12:03:27.554018Z",
      createdAt: "2026-09-21T15:22:49.170355Z",
    },
    employerId: 3,
    job: {
      id: 3,
      title: "Backend Engineer (Golang)",
      description:
        "Bergabunglah dengan tim Core Payment untuk membangun layanan pemrosesan transaksi berlatensi rendah. Kamu akan mengembangkan API yang dipakai ribuan merchant setiap harinya dengan target uptime 99,99%.",
      requirements:
        "- Minimal 3 tahun pengalaman backend development\n- Menguasai Go dan konsep concurrency (goroutine, channel)\n- Pengalaman dengan PostgreSQL dan Redis\n- Memahami prinsip idempotency dan konsistensi data pada sistem pembayaran\n- Terbiasa menulis unit test dan integration test",
      responsibilities:
        "- Membangun dan memelihara layanan pembayaran berbasis Go\n- Mengoptimalkan query database dan caching\n- Menangani insiden produksi bersama tim SRE\n- Menulis dokumentasi teknis dan API contract",
      benefits:
        "- Gaji kompetitif dan bonus tahunan berdasarkan kinerja\n- Asuransi kesehatan swasta termasuk rawat gigi dan kacamata\n- Hybrid 2 hari WFO\n- Makan siang gratis setiap hari kantor\n- Program kepemilikan saham karyawan (ESOP)",
      company: {
        id: 2,
        name: "PT Bayar Cepat Indonesia",
        slug: "pt-bayar-cepat-indonesia",
        tagline: "Pembayaran digital untuk semua",
        description:
          "PT Bayar Cepat Indonesia adalah perusahaan fintech penyedia layanan payment gateway dan dompet digital yang melayani lebih dari 40.000 merchant di seluruh Indonesia.",
        logoUrl:
          "https://ui-avatars.com/api/?name=Bayar+Cepat+Indonesia&background=2563EB&color=fff&size=256&bold=true",
        coverImageUrl:
          "https://picsum.photos/seed/bayar-cepat-indonesia/1200/400",
        website: "https://www.bayarcepatindonesia.com",
        email: "hr@bayarcepatindonesia.com",
        phone: "0217654321",
        foundedYear: 2016,
        companySize: "LARGE",
        companyType: "PRIVATE",
        industryType: "FINANCE",
        status: "ACTIVE",
        verified: true,
        active: true,
        ownerId: 3,
        socialLinks: [
          {
            platform: "LINKEDIN",
            url: "https://linkedin.com/company/bayar-cepat-indonesia",
          },
          {
            platform: "INSTAGRAM",
            url: "https://instagram.com/bayarcepatindonesia",
          },
          {
            platform: "WEBSITE",
            url: "https://www.bayarcepatindonesia.com",
          },
        ],
        createdAt: "2026-09-22T02:10:13.036633Z",
        updatedAt: "2026-09-22T02:12:58.220344Z",
      },
      employerId: 3,
      category: {
        id: 4,
        name: "Backend Development",
        slug: "backend-development",
        description:
          "Pekerjaan yang berfokus pada pengembangan sisi server, logika bisnis, RESTful API, dan manajemen database menggunakan teknologi seperti Java, Node.js, Python, dan Spring Boot.",
        iconUrl: "https://api.iconify.design/tabler/server.svg",
        active: true,
        parentId: 1,
        parentName: "Software Development",
        subCategories: [],
        createdAt: "2026-09-25T00:19:36.005262Z",
      },
      skills: [
        {
          id: 17,
          name: "Go",
          slug: "go",
          category: "PROGRAMMING_LANGUAGE",
          active: true,
        },
        {
          id: 5,
          name: "PostgreSQL",
          slug: "postgresql",
          category: "DATABASE",
          active: true,
        },
        {
          id: 6,
          name: "Redis",
          slug: "redis",
          category: "DATABASE",
          active: true,
        },
        {
          id: 8,
          name: "Docker",
          slug: "docker",
          category: "TOOL",
          active: true,
        },
        {
          id: 24,
          name: "Kafka",
          slug: "kafka",
          category: "TOOL",
          active: true,
        },
      ],
      tags: [
        {
          id: 6,
          name: "Stock Options",
          slug: "stock-options",
          active: true,
        },
        {
          id: 4,
          name: "Work Life Balance",
          slug: "work-life-balance",
          active: true,
        },
      ],
      address: "Jl. Jend. Sudirman Kav. 52-53, Equity Tower Lt. 30",
      city: "Jakarta Selatan",
      state: "DKI Jakarta",
      country: "Indonesia",
      zipCode: "12190",
      minSalary: 18000000,
      maxSalary: 28000000,
      currency: "IDR",
      salaryNegotiable: true,
      salaryDisclosed: true,
      jobType: "FULL_TIME",
      workMode: "HYBRID",
      experienceLevel: "MID_LEVEL",
      status: "OPEN",
      openings: 3,
      applicationDeadline: "2026-11-20",
      expiresAt: "2026-12-20",
      active: true,
      viewCount: 451,
      applicationCount: 41,
      createdAt: "2026-09-25T00:40:39.110713Z",
      updatedAt: "2026-09-25T00:42:39.208133Z",
      publishedAt: "2026-09-25T00:42:39.208133Z",
      closedAt: null,
    },
    company: {
      id: 2,
      name: "PT Bayar Cepat Indonesia",
      slug: "pt-bayar-cepat-indonesia",
      tagline: "Pembayaran digital untuk semua",
      description:
        "PT Bayar Cepat Indonesia adalah perusahaan fintech penyedia layanan payment gateway dan dompet digital yang melayani lebih dari 40.000 merchant di seluruh Indonesia.",
      logoUrl:
        "https://ui-avatars.com/api/?name=Bayar+Cepat+Indonesia&background=2563EB&color=fff&size=256&bold=true",
      coverImageUrl:
        "https://picsum.photos/seed/bayar-cepat-indonesia/1200/400",
      website: "https://www.bayarcepatindonesia.com",
      email: "hr@bayarcepatindonesia.com",
      phone: "0217654321",
      foundedYear: 2016,
      companySize: "LARGE",
      companyType: "PRIVATE",
      industryType: "FINANCE",
      status: "ACTIVE",
      verified: true,
      active: true,
      ownerId: 3,
      socialLinks: [
        {
          platform: "LINKEDIN",
          url: "https://linkedin.com/company/bayar-cepat-indonesia",
        },
        {
          platform: "INSTAGRAM",
          url: "https://instagram.com/bayarcepatindonesia",
        },
        {
          platform: "WEBSITE",
          url: "https://www.bayarcepatindonesia.com",
        },
      ],
      createdAt: "2026-09-22T02:10:13.036633Z",
      updatedAt: "2026-09-22T02:12:58.220344Z",
    },
    status: "PENDING",
    resumeId: 1,
    coverLetter:
      "Kepada Tim Rekrutmen PT Bayar Cepat Indonesia,\n\nSaya mengajukan lamaran untuk posisi Backend Engineer (Golang). Saya memiliki pengalaman enam tahun membangun sistem pembayaran, termasuk menurunkan p99 latency checkout sebesar 68% dan memimpin migrasi ke arsitektur event-driven berbasis Kafka.\n\nWalaupun bahasa utama saya selama ini adalah Java, dalam satu tahun terakhir saya menulis beberapa service internal dengan Golang, termasuk worker rekonsiliasi transaksi harian. Saya percaya pengalaman domain pembayaran saya dapat langsung memberi nilai bagi tim.\n\nTerima kasih atas waktu dan pertimbangannya.\n\nHormat saya,\nRina Kurniawati",
    expectedSalary: 26000000,
    availableFrom: "2026-12-01",
    isStarred: false,
    notes: [],
    screening: {
      score: 73,
      skillMatchScore: 68,
      experienceMatchScore: 80,
      educationMatchScore: 75,
      matchedSkills: ["PostgreSQL", "Redis", "Kafka"],
      missingSkills: ["Go", "Docker"],
      strengths: [
        "Pengalaman kuat di domain pembayaran yang sama dengan perusahaan",
        "Sudah membangun arsitektur event-driven berbasis Kafka",
      ],
      concerns: [
        "Pengalaman Golang baru sekitar 1 tahun dan terbatas pada service internal",
        "Tidak mencantumkan pengalaman Docker",
      ],
      summary:
        "Kandidat memiliki pengalaman domain yang sangat relevan, namun kemampuan Golang sebagai skill utama posisi ini masih terbatas. Layak dipertimbangkan jika tim siap memberi waktu adaptasi bahasa.",
    },
    withdrawnAt: "2026-09-28T02:05:47.331904Z",
    withdrawnReason: "Sudah menerima tawaran dari perusahaan lain.",
    appliedAt: "2026-09-25T11:48:02.775619Z",
    updatedAt: "2026-09-28T02:05:47.331904Z",
  },
  {
    id: 4,
    candidate: {
      id: 10,
      fullName: "Siti Rahmawati",
      email: "siti.rahmawati@gmail.com",
      phone: "081298765432",
      profileImage: null,
      role: "ROLE_JOB_SEEKER",
      status: "ACTIVE",
      lastLogin: "2026-09-29T07:21:08.114502Z",
      createdAt: "2026-09-20T03:11:45.660218Z",
    },
    employerId: 2,
    job: {
      id: 2,
      title: "Senior Frontend Engineer (React & TypeScript)",
      description:
        "Kami mencari Senior Frontend Engineer untuk memimpin pengembangan antarmuka platform job portal yang dipakai lebih dari 500.000 kandidat aktif. Kamu akan bertanggung jawab atas arsitektur frontend, design system, dan performa aplikasi di sisi klien, sekaligus menjadi rujukan teknis bagi tim frontend yang sedang tumbuh.",
      requirements:
        "- Minimal 5 tahun pengalaman frontend development, 3 tahun di antaranya dengan React\n- Penguasaan TypeScript, state management modern (Redux Toolkit / Zustand / TanStack Query)\n- Pengalaman membangun dan memelihara design system atau component library\n- Paham optimasi performa web: code splitting, lazy loading, Core Web Vitals\n- Terbiasa dengan testing: Jest, React Testing Library, Playwright atau Cypress\n- Memahami aksesibilitas (WCAG) dan responsive design\n- Nilai tambah: Next.js, SSR/ISR, dan micro-frontend",
      responsibilities:
        "- Merancang arsitektur frontend dan menetapkan standar teknis tim\n- Membangun komponen reusable dan merawat design system\n- Berkolaborasi erat dengan UI/UX Designer dan Backend Engineer\n- Melakukan code review dan menjaga kualitas kode\n- Memantau dan meningkatkan Core Web Vitals aplikasi produksi\n- Mentoring 3 frontend engineer level junior hingga mid",
      benefits:
        "- Gaji kompetitif dengan review tahunan\n- Fully remote dengan opsi coworking space yang ditanggung perusahaan\n- BPJS Kesehatan dan asuransi swasta untuk karyawan beserta keluarga\n- Budget perangkat kerja Rp 30.000.000 (MacBook Pro + monitor)\n- Budget belajar Rp 15.000.000 per tahun untuk kursus dan konferensi\n- 18 hari cuti tahunan dan kebijakan unlimited sick leave",
      company: {
        id: 1,
        name: "PT Teknologi Nusantara",
        slug: "pt-teknologi-nusantara",
        tagline: "Building the future of digital hiring",
        description:
          "PT Teknologi Nusantara adalah perusahaan teknologi yang fokus pada pengembangan platform job portal berbasis AI untuk mempertemukan talenta terbaik dengan perusahaan di Indonesia.",
        logoUrl:
          "https://ui-avatars.com/api/?name=Teknologi+Nusantara&background=7C3AED&color=fff&size=256&bold=true",
        coverImageUrl:
          "https://picsum.photos/seed/teknologi-nusantara/1200/400",
        website: "https://www.teknologinusantara.com",
        email: "hr@teknologinusantara.com",
        phone: "0211234567",
        foundedYear: 2018,
        companySize: "MEDIUM",
        companyType: "PRIVATE",
        industryType: "TECHNOLOGY",
        status: "ACTIVE",
        verified: true,
        active: true,
        ownerId: 2,
        socialLinks: [
          {
            platform: "LINKEDIN",
            url: "https://linkedin.com/company/teknologi-nusantara",
          },
          {
            platform: "INSTAGRAM",
            url: "https://instagram.com/teknologinusantara",
          },
          {
            platform: "WEBSITE",
            url: "https://www.teknologinusantara.com",
          },
        ],
        createdAt: "2026-09-21T01:10:13.036633Z",
        updatedAt: "2026-09-21T01:12:58.220344Z",
      },
      employerId: 2,
      category: {
        id: 2,
        name: "Frontend Development",
        slug: "frontend-development",
        description:
          "Kategori yang mencakup pengembangan antarmuka pengguna (UI) menggunakan teknologi web seperti HTML, CSS, JavaScript, dan framework modern seperti React, Vue, dan Angular.",
        iconUrl: "https://api.iconify.design/tabler/code.svg",
        active: true,
        parentId: 1,
        parentName: "Software Development",
        subCategories: [],
        createdAt: "2026-09-25T00:17:36.005262Z",
      },
      skills: [
        {
          id: 10,
          name: "Problem Solving",
          slug: "problem-solving",
          category: "SOFT_SKILL",
          active: true,
        },
        {
          id: 2,
          name: "TypeScript",
          slug: "typescript",
          category: "PROGRAMMING_LANGUAGE",
          active: true,
        },
        {
          id: 3,
          name: "React",
          slug: "react",
          category: "FRAMEWORK",
          active: true,
        },
      ],
      tags: [
        {
          id: 2,
          name: "Urgent Hiring",
          slug: "urgent-hiring",
          active: true,
        },
        {
          id: 5,
          name: "Flexible Hours",
          slug: "flexible-hours",
          active: true,
        },
        {
          id: 1,
          name: "Remote Friendly",
          slug: "remote-friendly",
          active: true,
        },
      ],
      address: null,
      city: "Jakarta",
      state: "DKI Jakarta",
      country: "Indonesia",
      zipCode: null,
      minSalary: 22000000,
      maxSalary: 35000000,
      currency: null,
      salaryNegotiable: null,
      salaryDisclosed: null,
      jobType: "FULL_TIME",
      workMode: "REMOTE",
      experienceLevel: "SENIOR_LEVEL",
      status: "OPEN",
      openings: 1,
      applicationDeadline: "2026-11-15",
      expiresAt: "2026-12-15",
      active: true,
      viewCount: null,
      applicationCount: null,
      createdAt: "2026-09-25T00:36:58.657067Z",
      updatedAt: "2026-09-25T00:38:22.151367Z",
      publishedAt: "2026-09-25T00:38:22.138354Z",
      closedAt: null,
    },
    company: {
      id: 1,
      name: "PT Teknologi Nusantara",
      slug: "pt-teknologi-nusantara",
      tagline: "Building the future of digital hiring",
      description:
        "PT Teknologi Nusantara adalah perusahaan teknologi yang fokus pada pengembangan platform job portal berbasis AI untuk mempertemukan talenta terbaik dengan perusahaan di Indonesia.",
      logoUrl:
        "https://ui-avatars.com/api/?name=Teknologi+Nusantara&background=7C3AED&color=fff&size=256&bold=true",
      coverImageUrl: "https://picsum.photos/seed/teknologi-nusantara/1200/400",
      website: "https://www.teknologinusantara.com",
      email: "hr@teknologinusantara.com",
      phone: "0211234567",
      foundedYear: 2018,
      companySize: "MEDIUM",
      companyType: "PRIVATE",
      industryType: "TECHNOLOGY",
      status: "ACTIVE",
      verified: true,
      active: true,
      ownerId: 2,
      socialLinks: [
        {
          platform: "LINKEDIN",
          url: "https://linkedin.com/company/teknologi-nusantara",
        },
        {
          platform: "INSTAGRAM",
          url: "https://instagram.com/teknologinusantara",
        },
        {
          platform: "WEBSITE",
          url: "https://www.teknologinusantara.com",
        },
      ],
      createdAt: "2026-09-21T01:10:13.036633Z",
      updatedAt: "2026-09-21T01:12:58.220344Z",
    },
    status: "SHORTLISTED",
    resumeId: 5,
    coverLetter:
      "Kepada Tim Rekrutmen PT Teknologi Nusantara,\n\nSaya ingin melamar posisi Senior Frontend Engineer (React & TypeScript). Selama lima tahun terakhir saya membangun aplikasi web berskala besar dengan React dan TypeScript, termasuk memimpin pembuatan design system internal yang dipakai oleh enam tim produk.\n\nSaya terbiasa mengoptimasi performa frontend: di proyek terakhir saya menurunkan Largest Contentful Paint dari 4,1 detik menjadi 1,8 detik melalui code splitting dan server-side rendering.\n\nSaya tertarik dengan misi perusahaan membangun platform rekrutmen berbasis AI dan siap berdiskusi lebih lanjut.\n\nHormat saya,\nSiti Rahmawati",
    expectedSalary: 32000000,
    availableFrom: "2026-11-01",
    isStarred: true,
    notes: [
      {
        id: 4,
        addByUserId: 2,
        content:
          "Portfolio design system sangat kuat dan relevan. Ekspektasi Rp 32.000.000 masih dalam range 22-35 juta. Masukkan ke shortlist untuk interview teknis.",
        createdAt: "2026-09-29T09:05:31.287415Z",
      },
    ],
    screening: {
      score: 92,
      skillMatchScore: 95,
      experienceMatchScore: 90,
      educationMatchScore: 85,
      matchedSkills: ["React", "TypeScript", "Problem Solving"],
      missingSkills: [],
      strengths: [
        "5 tahun pengalaman React dan TypeScript pada aplikasi berskala besar",
        "Memimpin pembuatan design system yang dipakai 6 tim produk",
        "Optimasi performa terukur (LCP turun dari 4,1 detik ke 1,8 detik)",
      ],
      concerns: ["Ekspektasi gaji Rp 32.000.000 mendekati batas atas range"],
      summary:
        "Kandidat sangat sesuai untuk posisi Senior Frontend Engineer. Semua skill yang dibutuhkan terpenuhi dan memiliki pengalaman kepemimpinan teknis yang kuat. Direkomendasikan untuk segera lanjut ke interview teknis.",
    },
    withdrawnAt: null,
    withdrawnReason: null,
    appliedAt: "2026-09-28T14:22:10.503917Z",
    updatedAt: "2026-09-29T09:05:31.287415Z",
  },
  {
    id: 5,
    candidate: {
      id: 11,
      fullName: "Budi Santoso",
      email: "budi.santoso@yahoo.com",
      phone: "085712345678",
      profileImage: null,
      role: "ROLE_JOB_SEEKER",
      status: "ACTIVE",
      lastLogin: "2026-09-30T02:48:55.902114Z",
      createdAt: "2026-09-27T10:30:12.448901Z",
    },
    employerId: 2,
    job: {
      id: 26,
      title: "QA Engineer (Manual & API Testing)",
      description:
        "Jaga kualitas platform job portal kami dengan melakukan pengujian menyeluruh sebelum setiap rilis. Posisi ini cocok untuk kamu yang teliti dan ingin berkembang ke arah automation.",
      requirements:
        "- Minimal 1 tahun pengalaman sebagai QA\n- Mampu menyusun test case dan test scenario\n- Pengalaman API testing dengan Postman\n- Memahami dasar SQL untuk validasi data\n- Nilai tambah: pengalaman dasar dengan Cypress",
      responsibilities:
        "- Menyusun dan menjalankan test case\n- Melakukan API testing dan regression testing\n- Melaporkan bug dengan jelas dan terstruktur\n- Berpartisipasi dalam sprint planning",
      benefits:
        "- Gaji kompetitif\n- Fully remote\n- BPJS Kesehatan dan asuransi swasta\n- Budget belajar Rp 5.000.000 per tahun",
      company: {
        id: 1,
        name: "PT Teknologi Nusantara",
        slug: "pt-teknologi-nusantara",
        tagline: "Building the future of digital hiring",
        description:
          "PT Teknologi Nusantara adalah perusahaan teknologi yang fokus pada pengembangan platform job portal berbasis AI untuk mempertemukan talenta terbaik dengan perusahaan di Indonesia.",
        logoUrl:
          "https://ui-avatars.com/api/?name=Teknologi+Nusantara&background=7C3AED&color=fff&size=256&bold=true",
        coverImageUrl:
          "https://picsum.photos/seed/teknologi-nusantara/1200/400",
        website: "https://www.teknologinusantara.com",
        email: "hr@teknologinusantara.com",
        phone: "0211234567",
        foundedYear: 2018,
        companySize: "MEDIUM",
        companyType: "PRIVATE",
        industryType: "TECHNOLOGY",
        status: "ACTIVE",
        verified: true,
        active: true,
        ownerId: 2,
        socialLinks: [
          {
            platform: "LINKEDIN",
            url: "https://linkedin.com/company/teknologi-nusantara",
          },
          {
            platform: "INSTAGRAM",
            url: "https://instagram.com/teknologinusantara",
          },
          {
            platform: "WEBSITE",
            url: "https://www.teknologinusantara.com",
          },
        ],
        createdAt: "2026-09-21T01:10:13.036633Z",
        updatedAt: "2026-09-21T01:12:58.220344Z",
      },
      employerId: 2,
      category: {
        id: 6,
        name: "Quality Assurance",
        slug: "quality-assurance",
        description:
          "Pengujian perangkat lunak secara manual maupun otomatis untuk memastikan kualitas dan keandalan produk.",
        iconUrl: "https://api.iconify.design/tabler/bug.svg",
        active: true,
        parentId: 1,
        parentName: "Software Development",
        subCategories: [],
        createdAt: "2026-09-25T00:21:36.005262Z",
      },
      skills: [
        {
          id: 30,
          name: "SQL",
          slug: "sql",
          category: "PROGRAMMING_LANGUAGE",
          active: true,
        },
        {
          id: 29,
          name: "Cypress",
          slug: "cypress",
          category: "TOOL",
          active: true,
        },
        {
          id: 40,
          name: "Teamwork",
          slug: "teamwork",
          category: "SOFT_SKILL",
          active: true,
        },
      ],
      tags: [
        {
          id: 1,
          name: "Remote Friendly",
          slug: "remote-friendly",
          active: true,
        },
        {
          id: 3,
          name: "Fresh Graduate",
          slug: "fresh-graduate",
          active: true,
        },
      ],
      address: null,
      city: "Jakarta",
      state: "DKI Jakarta",
      country: "Indonesia",
      zipCode: null,
      minSalary: 7000000,
      maxSalary: 11000000,
      currency: "IDR",
      salaryNegotiable: false,
      salaryDisclosed: true,
      jobType: "FULL_TIME",
      workMode: "REMOTE",
      experienceLevel: "JUNIOR_LEVEL",
      status: "OPEN",
      openings: 1,
      applicationDeadline: "2026-11-16",
      expiresAt: "2026-12-16",
      active: true,
      viewCount: 1702,
      applicationCount: 60,
      createdAt: "2026-09-25T10:15:38.192846Z",
      updatedAt: "2026-09-25T10:17:38.270486Z",
      publishedAt: "2026-09-25T10:17:38.270486Z",
      closedAt: null,
    },
    company: {
      id: 1,
      name: "PT Teknologi Nusantara",
      slug: "pt-teknologi-nusantara",
      tagline: "Building the future of digital hiring",
      description:
        "PT Teknologi Nusantara adalah perusahaan teknologi yang fokus pada pengembangan platform job portal berbasis AI untuk mempertemukan talenta terbaik dengan perusahaan di Indonesia.",
      logoUrl:
        "https://ui-avatars.com/api/?name=Teknologi+Nusantara&background=7C3AED&color=fff&size=256&bold=true",
      coverImageUrl: "https://picsum.photos/seed/teknologi-nusantara/1200/400",
      website: "https://www.teknologinusantara.com",
      email: "hr@teknologinusantara.com",
      phone: "0211234567",
      foundedYear: 2018,
      companySize: "MEDIUM",
      companyType: "PRIVATE",
      industryType: "TECHNOLOGY",
      status: "ACTIVE",
      verified: true,
      active: true,
      ownerId: 2,
      socialLinks: [
        {
          platform: "LINKEDIN",
          url: "https://linkedin.com/company/teknologi-nusantara",
        },
        {
          platform: "INSTAGRAM",
          url: "https://instagram.com/teknologinusantara",
        },
        {
          platform: "WEBSITE",
          url: "https://www.teknologinusantara.com",
        },
      ],
      createdAt: "2026-09-21T01:10:13.036633Z",
      updatedAt: "2026-09-21T01:12:58.220344Z",
    },
    status: "REJECTED",
    resumeId: 6,
    coverLetter:
      "Kepada Tim Rekrutmen PT Teknologi Nusantara,\n\nSaya mengajukan lamaran untuk posisi QA Engineer (Manual & API Testing). Saya lulusan Sistem Informasi dan memiliki pengalaman satu tahun sebagai QA di startup e-commerce, terbiasa menulis test case, melakukan regression testing, dan menguji API menggunakan Postman.\n\nSaya ingin terus berkembang di bidang quality assurance, termasuk mempelajari automation testing.\n\nTerima kasih atas kesempatan yang diberikan.\n\nHormat saya,\nBudi Santoso",
    expectedSalary: 13000000,
    availableFrom: "2026-10-15",
    isStarred: false,
    notes: [
      {
        id: 5,
        addByUserId: 2,
        content:
          "Ekspektasi gaji Rp 13.000.000 di atas budget (7-11 juta) dan pengalaman API testing masih terbatas. Tidak dilanjutkan untuk saat ini.",
        createdAt: "2026-09-30T04:12:44.019325Z",
      },
    ],
    screening: {
      score: 52,
      skillMatchScore: 45,
      experienceMatchScore: 50,
      educationMatchScore: 70,
      matchedSkills: ["SQL", "Teamwork"],
      missingSkills: ["Cypress"],
      strengths: [
        "Pengalaman 1 tahun sebagai QA di startup e-commerce",
        "Terbiasa menulis test case dan melakukan regression testing",
      ],
      concerns: [
        "Belum memiliki pengalaman automation testing dengan Cypress",
        "Pengalaman API testing masih terbatas",
        "Ekspektasi gaji Rp 13.000.000 di atas budget (Rp 7-11 juta)",
      ],
      summary:
        "Kandidat memiliki dasar QA manual yang cukup, namun belum memenuhi kebutuhan automation testing dan ekspektasi gaji melebihi budget. Kurang cocok untuk posisi ini saat ini.",
    },
    withdrawnAt: null,
    withdrawnReason: null,
    appliedAt: "2026-09-29T16:40:27.881256Z",
    updatedAt: "2026-09-30T04:12:44.019325Z",
  },
];
