export const resumes = [
  {
    id: 1,
    candidateId: 1,
    title: "Duarrrr Doe Maklen - Backend Engineer",
    template: "PROFESSIONAL",
    visibility: "PUBLIC",
    isDefault: true,
    personalInfo: {
      firstName: "Duarrrr",
      lastName: "Doe Maklen",
      headline: "Backend Engineer | Java & Spring Boot",
      email: "duarrrr.doemaklen@example.com",
      phone: "+62 812-3456-7890",
      city: "Jakarta",
      country: "Indonesia",
      linkedinUrl: "https://linkedin.com/in/duarrrr-doemaklen",
      githubUrl: "https://github.com/duarrrr",
      portfolioUrl: "https://duarrrr.dev",
      websiteUrl: "https://blog.duarrrr.dev",
    },
    summary:
      "Senior Backend Engineer dengan 6 tahun pengalaman membangun sistem pembayaran berskala besar. Menurunkan p99 latency checkout 68% dan memimpin migrasi monolit ke arsitektur event-driven berbasis Kafka untuk 2 juta transaksi harian. Menguasai Java, Spring Boot, PostgreSQL, dan Kubernetes. Mencari peran yang menuntut kepemilikan teknis atas sistem terdistribusi.",
    completionScore: 0,
    createdAt: "2026-09-25T00:42:06.911748Z",
    updatedAt: "2026-09-25T01:01:40.469418Z",
    workExperiences: [
      {
        id: 1,
        companyName: "Tokopedia",
        companyLogoUrl: "https://cdn.tokopedia.com/logo.png",
        jobTitle: "Senior Backend Engineer",
        employmentType: "FULL_TIME",
        location: "Jakarta Selatan, Indonesia",
        startDate: "2022-03-01",
        endDate: null,
        isCurrentJob: true,
        description:
          "Memimpin pengembangan microservices untuk modul pembayaran yang melayani 2 juta transaksi per hari. Menurunkan p99 latency checkout dari 1.2s menjadi 380ms melalui caching Redis dan optimasi query. Memimpin migrasi monolit ke arsitektur event-driven berbasis Kafka. Membimbing 3 engineer junior dan menetapkan standar code review tim.",
        technologies: [
          "Java 21",
          "Spring Boot 3",
          "PostgreSQL",
          "Kafka",
          "Redis",
          "Docker",
          "Kubernetes",
          "AWS",
        ],
        displayOrder: 0,
      },
      {
        id: 2,
        companyName: "Bukalapak",
        companyLogoUrl: "https://cdn.bukalapak.com/logo.png",
        jobTitle: "Software Engineer",
        employmentType: "FULL_TIME",
        location: "Jakarta Selatan, Indonesia",
        startDate: "2020-07-01",
        endDate: "2022-02-28",
        isCurrentJob: false,
        description:
          "Mengembangkan REST API katalog produk untuk 8 juta SKU dengan rata-rata 15.000 request per menit. Memisahkan modul inventaris dari monolit sehingga waktu deploy turun dari 40 menit menjadi 8 menit. Membangun pipeline CI/CD dengan GitHub Actions dan menaikkan cakupan pengujian dari 34% ke 71%.",
        technologies: [
          "Java 11",
          "Spring Boot 2",
          "MySQL",
          "RabbitMQ",
          "Jenkins",
          "GitHub Actions",
        ],
        displayOrder: 1,
      },
    ],
    educations: [
      {
        id: 1,
        institutionName: "Universitas Indonesia",
        degree: "Sarjana Komputer (S.Kom)",
        fieldOfStudy: "Teknik Informatika",
        grade: "3.72 / 4.00",
        startDate: "2016-08-01",
        endDate: "2020-06-30",
        isCurrentlyStudying: false,
        description:
          "Skripsi: Sistem Rekomendasi Lowongan Kerja Berbasis Collaborative Filtering. Asisten praktikum Struktur Data 3 semester.",
        displayOrder: 0,
      },
      {
        id: 2,
        institutionName: "SMA Negeri 8 Jakarta",
        degree: "SMA - IPA",
        fieldOfStudy: "Ilmu Pengetahuan Alam",
        grade: "88.4 / 100",
        startDate: "2013-07-01",
        endDate: "2016-05-31",
        isCurrentlyStudying: false,
        description: null,
        displayOrder: 1,
      },
    ],
    skills: [
      {
        id: 1,
        skillName: "Java",
        proficiencyLevel: "EXPERT",
        yearsOfExperience: 6,
        displayOrder: 0,
      },
      {
        id: 2,
        skillName: "Spring Boot",
        proficiencyLevel: "EXPERT",
        yearsOfExperience: 6,
        displayOrder: 1,
      },
      {
        id: 3,
        skillName: "PostgreSQL",
        proficiencyLevel: "ADVANCED",
        yearsOfExperience: 5,
        displayOrder: 2,
      },
      {
        id: 4,
        skillName: "JPA / Hibernate",
        proficiencyLevel: "ADVANCED",
        yearsOfExperience: 5,
        displayOrder: 3,
      },
      {
        id: 5,
        skillName: "Apache Kafka",
        proficiencyLevel: "ADVANCED",
        yearsOfExperience: 3,
        displayOrder: 4,
      },
      {
        id: 6,
        skillName: "Docker",
        proficiencyLevel: "ADVANCED",
        yearsOfExperience: 4,
        displayOrder: 5,
      },
    ],
    projects: [
      {
        id: 1,
        title: "Job Portal AI - Microservices Platform",
        description:
          "Platform pencarian kerja berbasis microservices dengan pencocokan kandidat-lowongan bertenaga AI. Terdiri dari 8 service (user, company, job, resume, application, preferences, notification, AI) dengan API Gateway, Service Registry, dan Config Server. Komunikasi asinkron via Kafka untuk notifikasi perubahan status lamaran, serta integrasi Gemini API untuk analisis resume dan skill gap.",
        technologies: [
          "Java 21",
          "Spring Boot 3",
          "Spring Cloud",
          "PostgreSQL",
          "Apache Kafka",
          "Docker",
          "Kubernetes",
          "Gemini API",
        ],
        projectUrl: "https://job-portal-ai.duarrrr.dev",
        sourceCodeUrl: "https://github.com/duarrrr/job-portal-ai",
        startDate: "2026-01-15",
        endDate: null,
        isOngoing: true,
        displayOrder: 0,
      },
      {
        id: 2,
        title: "Distributed Rate Limiter Library",
        description:
          "Library rate limiting terdistribusi untuk Spring Boot menggunakan algoritma sliding window log di atas Redis. Mendukung pembatasan per-user, per-IP, dan per-endpoint dengan konfigurasi anotasi. Menangani 50.000 request per detik pada pengujian beban dengan overhead p99 di bawah 3ms. Sudah dipublikasikan ke Maven Central dan diunduh lebih dari 1.200 kali.",
        technologies: [
          "Java 17",
          "Spring Boot",
          "Redis",
          "Lua",
          "JUnit 5",
          "Gatling",
        ],
        projectUrl: null,
        sourceCodeUrl:
          "https://github.com/duarrrr/spring-distributed-ratelimiter",
        startDate: "2024-06-01",
        endDate: "2024-11-30",
        isOngoing: false,
        displayOrder: 1,
      },
      {
        id: 3,
        title: "Event Sourcing Playground",
        description:
          "Implementasi event sourcing dan CQRS untuk studi kasus sistem perbankan sederhana, lengkap dengan event replay dan snapshot.",
        technologies: ["Java", "Spring Boot", "Kafka", "PostgreSQL"],
        projectUrl: null,
        sourceCodeUrl: "https://github.com/duarrrr/event-sourcing-playground",
        startDate: "2023-08-01",
        endDate: "2023-10-15",
        isOngoing: false,
        displayOrder: 2,
      },
    ],
    languages: [
      {
        id: 1,
        languageName: "Bahasa Indonesia",
        proficiency: "NATIVE",
        displayOrder: 0,
      },
      {
        id: 2,
        languageName: "English",
        proficiency: "PROFESSIONAL",
        displayOrder: 1,
      },
      {
        id: 3,
        languageName: "Javanese",
        proficiency: "FLUENT",
        displayOrder: 2,
      },
    ],
  },
  {
    id: 2,
    candidateId: 1,
    title: "Duarrrr Doe Maklen - Senior Frontend Engineer",
    template: "MODERN",
    visibility: "PUBLIC",
    isDefault: false,
    personalInfo: {
      firstName: "Duarrrr",
      lastName: "Doe Maklen",
      headline: "Senior Frontend Engineer | React, TypeScript & Design Systems",
      email: "duarrrr.doemaklen@example.com",
      phone: "+62 812-3456-7890",
      city: "Jakarta",
      country: "Indonesia",
      linkedinUrl: "https://linkedin.com/in/duarrrr-doemaklen",
      githubUrl: "https://github.com/duarrrr",
      portfolioUrl: "https://duarrrr.dev",
      websiteUrl: "https://blog.duarrrr.dev",
    },
    summary:
      "Senior Frontend Engineer dengan 6 tahun pengalaman membangun antarmuka berskala besar dengan React dan TypeScript. Memimpin design system yang dipakai 12 tim produk dan menaikkan skor Core Web Vitals halaman checkout dari 42 ke 91 lewat code splitting serta pengurangan bundle 38%. Menguasai Next.js, Redux Toolkit, TanStack Query, dan pengujian dengan Jest serta Playwright hingga cakupan 78%. Mencari peran yang menuntut kepemilikan arsitektur frontend dan mentoring tim.",
    completionScore: 0,
    createdAt: "2026-09-25T00:44:22.004140Z",
    updatedAt: "2026-09-25T01:02:36.178575Z",
    workExperiences: [
      {
        id: 3,
        companyName: "Tokopedia",
        companyLogoUrl: "https://cdn.tokopedia.com/logo.png",
        jobTitle: "Senior Frontend Engineer",
        employmentType: "FULL_TIME",
        location: "Jakarta Selatan, Indonesia",
        startDate: "2022-03-01",
        endDate: null,
        isCurrentJob: true,
        description:
          "Memimpin pengembangan design system yang dipakai 12 tim produk, mencakup 60+ komponen React dengan dokumentasi Storybook. Menaikkan skor Core Web Vitals halaman checkout dari 42 menjadi 91 lewat code splitting, lazy loading, dan pengurangan bundle sebesar 38%. Menetapkan standar aksesibilitas WCAG AA di seluruh alur pembayaran. Membimbing 3 frontend engineer level junior hingga mid.",
        technologies: [
          "React 18",
          "TypeScript",
          "Next.js",
          "Redux Toolkit",
          "TanStack Query",
          "Tailwind CSS",
          "Storybook",
          "Vite",
        ],
        displayOrder: 0,
      },
      {
        id: 4,
        companyName: "Bukalapak",
        companyLogoUrl: "https://cdn.bukalapak.com/logo.png",
        jobTitle: "Frontend Engineer",
        employmentType: "FULL_TIME",
        location: "Jakarta Selatan, Indonesia",
        startDate: "2020-07-01",
        endDate: "2022-02-28",
        isCurrentJob: false,
        description:
          "Membangun ulang halaman pencarian produk dengan React dan TypeScript, menurunkan bounce rate 17% dan mempercepat waktu render awal 2.1 detik. Memigrasikan 40+ komponen dari JavaScript ke TypeScript tanpa downtime. Menyiapkan pipeline pengujian dengan Jest dan Playwright hingga cakupan 78%.",
        technologies: [
          "React 17",
          "TypeScript",
          "Redux",
          "Sass",
          "Jest",
          "Playwright",
          "Webpack",
        ],
        displayOrder: 1,
      },
    ],
    educations: [
      {
        id: 3,
        institutionName: "Institut Teknologi Bandung",
        degree: "Magister Teknik Informatika (M.T.)",
        fieldOfStudy: "Rekayasa Perangkat Lunak",
        grade: "3.85 / 4.00",
        startDate: "2025-09-01",
        endDate: null,
        isCurrentlyStudying: true,
        description:
          "Konsentrasi Distributed Systems. Riset tesis tentang konsistensi eventual pada arsitektur event-driven.",
        displayOrder: 0,
      },
    ],
    skills: [
      {
        id: 7,
        skillName: "React",
        proficiencyLevel: "EXPERT",
        yearsOfExperience: 6,
        displayOrder: 0,
      },
      {
        id: 8,
        skillName: "TypeScript",
        proficiencyLevel: "EXPERT",
        yearsOfExperience: 5,
        displayOrder: 1,
      },
      {
        id: 9,
        skillName: "JavaScript (ES2023)",
        proficiencyLevel: "EXPERT",
        yearsOfExperience: 6,
        displayOrder: 2,
      },
      {
        id: 10,
        skillName: "HTML5 & CSS3",
        proficiencyLevel: "ADVANCED",
        yearsOfExperience: 6,
        displayOrder: 3,
      },
      {
        id: 11,
        skillName: "Next.js",
        proficiencyLevel: "ADVANCED",
        yearsOfExperience: 4,
        displayOrder: 4,
      },
      {
        id: 12,
        skillName: "Redux Toolkit",
        proficiencyLevel: "ADVANCED",
        yearsOfExperience: 4,
        displayOrder: 5,
      },
      {
        id: 13,
        skillName: "Tailwind CSS",
        proficiencyLevel: "ADVANCED",
        yearsOfExperience: 3,
        displayOrder: 6,
      },
    ],
    projects: [
      {
        id: 4,
        title: "Nusa UI - React Component Library",
        description:
          "Component library open source berisi 64 komponen React dengan dukungan tema terang/gelap, aksesibilitas WCAG AA, dan tree-shaking penuh. Dilengkapi dokumentasi Storybook interaktif, design token berbasis CSS custom properties, serta uji visual regression dengan Chromatic. Bundle size 18 kB gzip untuk import penuh, dan sudah dipakai di 3 produk internal.",
        technologies: [
          "React 18",
          "TypeScript",
          "Vite",
          "Storybook",
          "Radix UI",
          "Tailwind CSS",
          "Chromatic",
          "Vitest",
        ],
        projectUrl: "https://nusa-ui.duarrrr.dev",
        sourceCodeUrl: "https://github.com/duarrrr/nusa-ui",
        startDate: "2025-09-01",
        endDate: null,
        isOngoing: true,
        displayOrder: 0,
      },
      {
        id: 5,
        title: "Web Vitals Dashboard",
        description:
          "Dashboard pemantauan Core Web Vitals yang mengumpulkan data RUM langsung dari browser pengunjung tanpa layanan pihak ketiga. Menampilkan LCP, INP, dan CLS per halaman dengan breakdown perangkat dan koneksi, serta memberi peringatan saat metrik melewati ambang batas. Berhasil mengidentifikasi tiga regresi performa pada situs produksi dalam bulan pertama pemakaian.",
        technologies: [
          "Next.js 14",
          "TypeScript",
          "web-vitals",
          "Recharts",
          "TanStack Query",
          "PostgreSQL",
        ],
        projectUrl: "https://vitals.duarrrr.dev",
        sourceCodeUrl: "https://github.com/duarrrr/web-vitals-dashboard",
        startDate: "2025-02-01",
        endDate: "2025-07-20",
        isOngoing: false,
        displayOrder: 1,
      },
      {
        id: 6,
        title: "Offline-First Notes PWA",
        description:
          "Aplikasi catatan progressive web app dengan sinkronisasi offline-first menggunakan IndexedDB dan conflict resolution berbasis last-write-wins.",
        technologies: ["React", "TypeScript", "Workbox", "IndexedDB", "Vite"],
        projectUrl: null,
        sourceCodeUrl: "https://github.com/duarrrr/offline-notes-pwa",
        startDate: "2024-04-01",
        endDate: "2024-06-30",
        isOngoing: false,
        displayOrder: 2,
      },
    ],
    languages: [
      {
        id: 4,
        languageName: "Bahasa Indonesia",
        proficiency: "NATIVE",
        displayOrder: 0,
      },
      {
        id: 5,
        languageName: "English",
        proficiency: "PROFESSIONAL",
        displayOrder: 1,
      },
      {
        id: 6,
        languageName: "Japanese",
        proficiency: "CONVERSATIONAL",
        displayOrder: 2,
      },
    ],
  },
];
